package com.qinghe.life.service.impl;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.qinghe.life.common.PageResult;
import com.qinghe.life.dto.*;
import com.qinghe.life.entity.*;
import com.qinghe.life.exception.BusinessException;
import com.qinghe.life.mapper.*;
import com.qinghe.life.service.DormAssetService;
import com.qinghe.life.service.DormAssetHealth;
import com.qinghe.life.utils.AdminContext;
import com.qinghe.life.vo.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.security.SecureRandom;
import java.util.*;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class DormAssetServiceImpl implements DormAssetService {
    /** 实时只读门禁确认的 qh_building.building_type 宿舍目录取值。 */
    private static final String DORM_BUILDING_TYPE = "宿舍楼";
    private static final SecureRandom RANDOM = new SecureRandom();
    private static final LinkedHashMap<String, String> ASSET_ITEMS = assetItems();
    private static final Set<String> ASSET_STATUSES = new LinkedHashSet<String>(Arrays.asList("NORMAL", "REPAIR", "SCRAPPED"));
    private final CampusMapper campusMapper; private final BuildingMapper buildingMapper; private final DormRoomMapper roomMapper;
    private final DormBedMapper bedMapper; private final AssetSetMapper assetSetMapper; private final AssetMapper assetMapper; private final DormCheckinMapper checkinMapper;

    public DormAssetServiceImpl(CampusMapper campusMapper, BuildingMapper buildingMapper, DormRoomMapper roomMapper, DormBedMapper bedMapper, AssetSetMapper assetSetMapper, AssetMapper assetMapper, DormCheckinMapper checkinMapper) {
        this.campusMapper=campusMapper; this.buildingMapper=buildingMapper; this.roomMapper=roomMapper; this.bedMapper=bedMapper; this.assetSetMapper=assetSetMapper; this.assetMapper=assetMapper; this.checkinMapper=checkinMapper;
    }

    @Override public List<CampusVO> listAvailableCampuses() { admin(); return campusMapper.selectList(Wrappers.<Campus>lambdaQuery().eq(Campus::getStatus,1).orderByAsc(Campus::getSortOrder).orderByAsc(Campus::getId)).stream().map(CampusVO::fromCampus).collect(Collectors.toList()); }

    @Override public PageResult<AdminDormBuildingVO> listBuildings(AdminDormBuildingQuery query) {
        admin(); requireEnabledCampus(query.getCampusId()); String keyword=trim(query.getKeyword()); IPage<Building> data=buildingMapper.selectPage(new Page<Building>(query.getPage(),query.getSize()), Wrappers.<Building>lambdaQuery().eq(Building::getBuildingType,DORM_BUILDING_TYPE).eq(Building::getCampusId,query.getCampusId()).eq(query.getStatus()!=null,Building::getStatus,query.getStatus()).and(keyword!=null,item->item.like(Building::getBuildingCode,keyword).or().like(Building::getBuildingName,keyword)).orderByAsc(Building::getCampusId).orderByAsc(Building::getSortOrder).orderByAsc(Building::getId));
        return new PageResult<AdminDormBuildingVO>(buildingViews(data.getRecords()),data.getTotal(),data.getCurrent(),data.getSize());
    }
    @Override public List<AdminDormBuildingVO> listAvailableBuildings(Long campusId) { admin(); if(campusId!=null) requireEnabledCampus(campusId); return buildingViews(buildingMapper.selectList(Wrappers.<Building>lambdaQuery().eq(Building::getBuildingType,DORM_BUILDING_TYPE).eq(campusId!=null,Building::getCampusId,campusId).eq(Building::getStatus,1).orderByAsc(Building::getSortOrder).orderByAsc(Building::getBuildingName))); }
    @Override public AdminDormBuildingVO buildingDetail(Long buildingId) { admin(); return buildingView(requireDormBuilding(buildingId)); }
    @Override @Transactional(rollbackFor=Exception.class) public AdminDormBuildingVO createBuilding(AdminDormBuildingCreateRequest request) { admin(); Campus campus=requireEnabledCampus(request.getCampusId()); String code=normalizeCode(request.getBuildingCode()); String name=requiredText(request.getBuildingName(),"楼栋名称不能为空"); ensureCodeUnique(campus.getId(),code,null); ensureNameUnique(campus.getId(),name,null); Building item=new Building(); item.setCampusId(campus.getId()); item.setBuildingCode(code); item.setBuildingName(name); item.setBuildingType(DORM_BUILDING_TYPE); item.setArea(trim(request.getArea())); item.setRemark(trim(request.getRemark())); item.setStatus(request.getStatus()); item.setSortOrder(0); try { buildingMapper.insert(item); } catch(DuplicateKeyException ex) { throw new BusinessException("同一校区内楼栋编码或名称已存在"); } return buildingView(item); }
    @Override @Transactional(rollbackFor=Exception.class) public AdminDormBuildingVO updateBuilding(Long buildingId, AdminDormBuildingUpdateRequest request) { admin(); Building item=requireDormBuilding(buildingId); requireEnabledCampus(item.getCampusId()); BuildingStats stats=buildingResources(item.getId()); String code=normalizeCode(request.getBuildingCode()); if(!code.equals(item.getBuildingCode())&&stats.hasDormResources) throw new BusinessException("该楼栋已生成宿舍资源，不能修改楼栋编码。"); if(Integer.valueOf(0).equals(request.getStatus())&&stats.currentCheckinCount>0) throw new BusinessException("该楼栋仍有当前入住，请先办理退宿或换寝。"); String name=requiredText(request.getBuildingName(),"楼栋名称不能为空"); ensureCodeUnique(item.getCampusId(),code,item.getId()); ensureNameUnique(item.getCampusId(),name,item.getId()); item.setBuildingCode(code); item.setBuildingName(name); item.setArea(trim(request.getArea())); item.setRemark(trim(request.getRemark())); item.setStatus(request.getStatus()); try { buildingMapper.updateById(item); } catch(DuplicateKeyException ex) { throw new BusinessException("同一校区内楼栋编码或名称已存在"); } return buildingView(item); }
    @Override @Transactional(rollbackFor=Exception.class) public void updateBuildingStatus(Long buildingId,DormBuildingStatusRequest request) { admin(); Building item=requireDormBuilding(buildingId); requireEnabledCampus(item.getCampusId()); if(Integer.valueOf(0).equals(request.getStatus())&&buildingResources(item.getId()).currentCheckinCount>0) throw new BusinessException("该楼栋仍有当前入住，请先办理退宿或换寝。"); item.setStatus(request.getStatus()); buildingMapper.updateById(item); }
    @Override @Transactional(rollbackFor=Exception.class) public void deleteBuilding(Long buildingId) { admin(); Building item=requireDormBuilding(buildingId); BuildingStats stats=buildingResources(item.getId()); if(stats.currentCheckinCount>0) throw new BusinessException("该楼栋仍有当前入住，不能删除；请先办理退宿或换寝。"); if(stats.checkinHistoryCount>0) throw new BusinessException("该楼栋已有入住历史，不能物理删除；请停用。"); if(stats.assetSetCount>0) throw new BusinessException("该楼栋已有资产套装，不能物理删除；请停用。"); if(stats.bedCount>0) throw new BusinessException("该楼栋已有床位，不能物理删除；请停用。"); if(stats.roomCount>0) throw new BusinessException("该楼栋已有寝室，不能物理删除；请停用。"); buildingMapper.deleteById(item.getId()); }
    @Override @Transactional(rollbackFor=Exception.class) public void updateBuildingCode(Long buildingId,BuildingCodeUpdateRequest request) { admin(); Building item=requireDormBuilding(buildingId); String code=normalizeCode(request.getBuildingCode()); if(!code.equals(item.getBuildingCode())&&buildingResources(item.getId()).hasDormResources) throw new BusinessException("该楼栋已生成宿舍资源，不能修改楼栋编码。"); ensureCodeUnique(item.getCampusId(),code,item.getId()); item.setBuildingCode(code); try { buildingMapper.updateById(item); } catch(DuplicateKeyException ex) { throw new BusinessException("同一校区内楼栋编码已存在"); } }

    @Override @Transactional(rollbackFor=Exception.class) public DormRoomVO createRoom(DormRoomSaveRequest request) { admin(); Building building=requireEnabledDormBuilding(request.getBuildingId()); String roomNo=requiredText(request.getRoomNo(),"寝室号不能为空"); ensureRoomNoUnique(building.getId(),roomNo,null); DormRoom room=new DormRoom(); room.setCampusId(building.getCampusId()); room.setBuildingId(building.getId()); room.setRoomNo(roomNo); room.setFloor(trim(request.getFloor())); room.setCapacity(request.getCapacity()); room.setStatus(request.getStatus()); room.setRemark(trim(request.getRemark())); try { roomMapper.insert(room); } catch(DuplicateKeyException ex) { throw new BusinessException(409,"同一楼栋内寝室号已存在"); } return roomView(room); }
    @Override public PageResult<DormRoomVO> listRooms(Long buildingId,PageQuery pageQuery) { admin(); if(buildingId!=null) requireDormBuilding(buildingId); IPage<DormRoom> data=roomMapper.selectPage(new Page<DormRoom>(pageQuery.getPage(),pageQuery.getSize()),Wrappers.<DormRoom>lambdaQuery().eq(buildingId!=null,DormRoom::getBuildingId,buildingId).orderByAsc(DormRoom::getRoomNo)); return new PageResult<DormRoomVO>(data.getRecords().stream().map(this::roomView).collect(Collectors.toList()),data.getTotal(),data.getCurrent(),data.getSize()); }
    @Override @Transactional(rollbackFor=Exception.class) public DormRoomVO updateRoom(Long roomId,DormRoomUpdateRequest request) { admin(); DormRoom room=requireRoom(roomId); requireDormBuilding(room.getBuildingId()); RoomStats stats=roomStats(roomId); String no=requiredText(request.getRoomNo(),"寝室号不能为空"); if(!no.equals(room.getRoomNo())&&stats.assetSetCount>0) throw new BusinessException("该寝室已有资产套装，不能修改寝室号。"); ensureRoomNoUnique(room.getBuildingId(),no,room.getId()); if(request.getCapacity()<stats.bedCount) throw new BusinessException("寝室容量不能小于现有床位数。"); if(Integer.valueOf(0).equals(request.getStatus())&&stats.currentCheckinCount>0) throw new BusinessException("该寝室仍有当前入住，请先办理退宿或换寝。"); room.setRoomNo(no); room.setFloor(trim(request.getFloor())); room.setCapacity(request.getCapacity()); room.setStatus(request.getStatus()); room.setRemark(trim(request.getRemark())); try { roomMapper.updateById(room); } catch(DuplicateKeyException ex) { throw new BusinessException(409,"同一楼栋内寝室号已存在"); } return roomView(room); }
    @Override @Transactional(rollbackFor=Exception.class) public void updateRoomStatus(Long roomId,DormDirectoryStatusRequest request) { admin(); DormRoom room=requireRoom(roomId); requireDormBuilding(room.getBuildingId()); if(Integer.valueOf(0).equals(request.getStatus())&&roomStats(roomId).currentCheckinCount>0) throw new BusinessException("该寝室仍有当前入住，请先办理退宿或换寝。"); room.setStatus(request.getStatus()); roomMapper.updateById(room); }
    @Override @Transactional(rollbackFor=Exception.class) public void deleteRoom(Long roomId) { admin(); DormRoom room=requireRoom(roomId); requireDormBuilding(room.getBuildingId()); RoomStats stats=roomStats(roomId); if(stats.currentCheckinCount>0) throw new BusinessException("该寝室仍有当前入住，不能删除。"); if(stats.bedCount>0) throw new BusinessException("该寝室已有床位、资产或入住历史，不能物理删除；请停用。"); roomMapper.deleteById(roomId); }

    @Override @Transactional(rollbackFor=Exception.class) public DormBedVO createBed(Long roomId,DormBedSaveRequest request) { admin(); DormRoom room=requireRoom(roomId); requireEnabledDormBuilding(room.getBuildingId()); if(!Integer.valueOf(1).equals(room.getStatus())) throw new BusinessException("寝室已停用，不能新增床位"); if(roomStats(roomId).bedCount>=room.getCapacity()) throw new BusinessException("床位数不能超过寝室容量"); DormBed bed=new DormBed(); bed.setDormRoomId(roomId); bed.setBedNo(requiredText(request.getBedNo(),"床位号不能为空")); bed.setStatus(1); bed.setRemark(trim(request.getRemark())); try { bedMapper.insert(bed); } catch(DuplicateKeyException ex) { throw new BusinessException("同一寝室内床位号已存在"); } return bedView(bed); }
    @Override public List<DormBedVO> listBeds(Long roomId) { admin(); DormRoom room=requireRoom(roomId); requireDormBuilding(room.getBuildingId()); return bedMapper.selectList(Wrappers.<DormBed>lambdaQuery().eq(DormBed::getDormRoomId,roomId).orderByAsc(DormBed::getBedNo)).stream().map(this::bedView).collect(Collectors.toList()); }
    @Override @Transactional(rollbackFor=Exception.class) public DormBedVO updateBed(Long bedId,DormBedUpdateRequest request) { admin(); DormBed bed=requireBed(bedId); DormRoom room=requireRoom(bed.getDormRoomId()); requireDormBuilding(room.getBuildingId()); AssetSet set=findAssetSet(bedId); if(!requiredText(request.getBedNo(),"床位号不能为空").equals(bed.getBedNo())&&set!=null) throw new BusinessException("该床位已有资产套装，不能修改床位号。"); if(Integer.valueOf(0).equals(request.getStatus())&&activeCheckinsForBed(bedId)>0) throw new BusinessException("该床位仍有当前入住，请先办理退宿或换寝。"); bed.setBedNo(requiredText(request.getBedNo(),"床位号不能为空")); bed.setStatus(request.getStatus()); bed.setRemark(trim(request.getRemark())); try { bedMapper.updateById(bed); } catch(DuplicateKeyException ex) { throw new BusinessException("同一寝室内床位号已存在"); } return bedView(bed); }
    @Override @Transactional(rollbackFor=Exception.class) public void updateBedStatus(Long bedId,DormDirectoryStatusRequest request) { admin(); DormBed bed=requireBed(bedId); DormRoom room=requireRoom(bed.getDormRoomId()); requireDormBuilding(room.getBuildingId()); if(Integer.valueOf(0).equals(request.getStatus())&&activeCheckinsForBed(bedId)>0) throw new BusinessException("该床位仍有当前入住，请先办理退宿或换寝。"); bed.setStatus(request.getStatus()); bedMapper.updateById(bed); }
    @Override @Transactional(rollbackFor=Exception.class) public void deleteBed(Long bedId) { admin(); DormBed bed=requireBed(bedId); DormRoom room=requireRoom(bed.getDormRoomId()); requireDormBuilding(room.getBuildingId()); if(activeCheckinsForBed(bedId)>0) throw new BusinessException("该床位仍有当前入住，不能删除。"); if(findAssetSet(bedId)!=null||checkinMapper.selectCount(Wrappers.<DormCheckin>lambdaQuery().eq(DormCheckin::getDormBedId,bedId))>0) throw new BusinessException("该床位已有资产套装或入住历史，不能物理删除；请停用。"); bedMapper.deleteById(bedId); }

    @Override @Transactional(rollbackFor=Exception.class) public AssetSetDetailVO generateAssetSet(Long bedId) { admin(); DormBed bed=requireBed(bedId); DormRoom room=requireRoom(bed.getDormRoomId()); Building building=requireEnabledDormBuilding(room.getBuildingId()); if(!Integer.valueOf(1).equals(room.getStatus())||!Integer.valueOf(1).equals(bed.getStatus())) throw new BusinessException("停用目录不能初始化资产套装"); AssetSet set=findAssetSet(bedId); if(set==null) { if(trim(building.getBuildingCode())==null) throw new BusinessException("请先维护楼栋编码"); set=new AssetSet(); set.setDormBedId(bedId); set.setAssetSetNo(building.getBuildingCode().trim()+room.getRoomNo()+"-"+bed.getBedNo()); set.setQrToken(nextToken()); set.setQrStatus(1); set.setStatus("AVAILABLE"); try { assetSetMapper.insert(set); } catch(DuplicateKeyException ex) { set=findAssetSet(bedId); if(set==null) throw ex; } } ensureAssets(set.getId()); return detail(set); }
    @Override @Transactional(rollbackFor=Exception.class) public AssetSetDetailVO supplementFixedAssets(Long bedId) { admin(); DormBed bed=requireBed(bedId); AssetSet set=findAssetSet(bed.getId()); if(set==null) throw new BusinessException(404,"该床位尚未生成资产套装"); ensureAssets(set.getId()); return detail(set); }
    @Override public AssetSetDetailVO getAssetSet(Long bedId) { admin(); DormBed bed=requireBed(bedId); DormRoom room=requireRoom(bed.getDormRoomId()); requireDormBuilding(room.getBuildingId()); AssetSet set=findAssetSet(bedId); if(set==null) throw new BusinessException(404,"该床位尚未生成资产套装"); return detail(set); }
    @Override @Transactional(rollbackFor=Exception.class) public AssetVO updateAsset(Long assetId,AssetUpdateRequest request) { admin(); Asset asset=assetMapper.selectById(assetId); if(asset==null) throw new BusinessException(404,"资产不存在"); String status=requiredText(request.getAssetStatus(),"资产状态不能为空"); if(!ASSET_STATUSES.contains(status)) throw new BusinessException("资产状态不支持"); asset.setAssetStatus(status); asset.setRemark(trim(request.getRemark())); assetMapper.updateById(asset); return AssetVO.from(asset); }
    @Override public byte[] qrPng(Long assetSetId) { admin(); return qr("QH-DORM-V1:"+requireAssetSet(assetSetId).getQrToken()); }
    @Override public byte[] qrZip(List<Long> ids) { admin(); if(ids==null||ids.isEmpty()) throw new BusinessException("请选择至少一个资产套装"); try { ByteArrayOutputStream bytes=new ByteArrayOutputStream(); ZipOutputStream zip=new ZipOutputStream(bytes); for(Long id:new LinkedHashSet<Long>(ids)){ AssetSet set=requireAssetSet(id); zip.putNextEntry(new ZipEntry(set.getAssetSetNo()+".png")); zip.write(qr("QH-DORM-V1:"+set.getQrToken())); zip.closeEntry(); } zip.finish(); return bytes.toByteArray(); } catch(IOException ex) { throw new BusinessException(500,"二维码压缩包生成失败"); } }

    private AdminDormBuildingVO buildingView(Building item) { return buildingView(item,buildingResources(item.getId()),campusMapper.selectById(item.getCampusId())); }
    private List<AdminDormBuildingVO> buildingViews(List<Building> records) { if(records.isEmpty()) return Collections.emptyList(); List<Long> buildingIds=records.stream().map(Building::getId).collect(Collectors.toList()); Map<Long,BuildingStats> stats=buildingResources(buildingIds); Map<Long,Campus> campuses=campusMapper.selectBatchIds(records.stream().map(Building::getCampusId).collect(Collectors.toSet())).stream().collect(Collectors.toMap(Campus::getId,item->item)); return records.stream().map(item->buildingView(item,stats.get(item.getId()),campuses.get(item.getCampusId()))).collect(Collectors.toList()); }
    private AdminDormBuildingVO buildingView(Building item,BuildingStats stats,Campus campus) { AdminDormBuildingVO view=new AdminDormBuildingVO(); view.setId(item.getId()); view.setCampusId(item.getCampusId()); view.setCampusName(campus==null?"已归档校区":campus.getCampusName()); view.setBuildingCode(item.getBuildingCode()); view.setBuildingName(item.getBuildingName()); view.setBuildingType(item.getBuildingType()); view.setArea(item.getArea()); view.setRemark(item.getRemark()); view.setStatus(item.getStatus()); view.setRoomCount(stats.roomCount); view.setBedCount(stats.bedCount); view.setCurrentCheckinCount(stats.currentCheckinCount); view.setCodeEditable(!stats.hasDormResources); return view; }
    private DormRoomVO roomView(DormRoom room) { RoomStats stats=roomStats(room.getId()); DormRoomVO view=DormRoomVO.from(room); view.setBedCount(stats.bedCount); view.setCurrentCheckinCount(stats.currentCheckinCount); view.setRoomNoEditable(stats.assetSetCount==0); return view; }
 private DormBedVO bedView(DormBed bed) { DormBedVO view=DormBedVO.from(bed); AssetSet set=findAssetSet(bed.getId()); view.setCurrentCheckin(activeCheckinsForBed(bed.getId())>0); view.setBedNoEditable(set==null); if(set!=null){ DormAssetHealth.Result health=DormAssetHealth.inspect(assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,set.getId()))); view.setAssetSetId(set.getId()); view.setAssetSetNo(set.getAssetSetNo()); view.setAssetSetStatus(set.getStatus()); view.setQrStatus(set.getQrStatus()); view.setAssetHealthStatus(health.getStatus()); view.setAssetAbnormal(health.isAbnormal()); } return view; }
    private AssetSetDetailVO detail(AssetSet set) { List<Asset> records=assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,set.getId()).orderByAsc(Asset::getId)); List<AssetVO> assets=records.stream().map(AssetVO::from).collect(Collectors.toList()); DormAssetHealth.Result health=DormAssetHealth.inspect(records); AssetSetDetailVO view=AssetSetDetailVO.from(set,assets); view.setCurrentCheckin(activeCheckinsForBed(set.getDormBedId())>0); view.setHealthStatus(health.getStatus()); view.setAssetAbnormal(health.isAbnormal()); return view; }
    private BuildingStats buildingResources(Long buildingId) { return buildingResources(Collections.singletonList(buildingId)).get(buildingId); }
    private Map<Long,BuildingStats> buildingResources(Collection<Long> buildingIds) { Map<Long,BuildingStats> result=new HashMap<Long,BuildingStats>(); if(buildingIds==null||buildingIds.isEmpty()) return result; for(Long id:buildingIds) result.put(id,new BuildingStats(0,0,0,0,0)); for(DormBuildingStats row:buildingMapper.selectDormBuildingStats(buildingIds)) result.put(row.getBuildingId(),new BuildingStats(number(row.getRoomCount()),number(row.getBedCount()),number(row.getAssetSetCount()),number(row.getCheckinHistoryCount()),number(row.getCurrentCheckinCount()))); return result; }
    private RoomStats roomStats(Long roomId) { List<DormBed> beds=bedMapper.selectList(Wrappers.<DormBed>lambdaQuery().eq(DormBed::getDormRoomId,roomId)); if(beds.isEmpty()) return new RoomStats(0,0,0); List<Long> ids=beds.stream().map(DormBed::getId).collect(Collectors.toList()); long sets=assetSetMapper.selectCount(Wrappers.<AssetSet>lambdaQuery().in(AssetSet::getDormBedId,ids)); long active=checkinMapper.selectCount(Wrappers.<DormCheckin>lambdaQuery().in(DormCheckin::getDormBedId,ids).eq(DormCheckin::getActiveFlag,1)); return new RoomStats(beds.size(),sets,active); }
    private long activeCheckinsForBed(Long bedId) { return checkinMapper.selectCount(Wrappers.<DormCheckin>lambdaQuery().eq(DormCheckin::getDormBedId,bedId).eq(DormCheckin::getActiveFlag,1)); }
    private AssetSet findAssetSet(Long bedId) { return assetSetMapper.selectOne(Wrappers.<AssetSet>lambdaQuery().eq(AssetSet::getDormBedId,bedId)); }
    private void ensureAssets(Long setId) { Set<String> existing=assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,setId)).stream().map(Asset::getAssetType).collect(Collectors.toSet()); for(Map.Entry<String,String> item:ASSET_ITEMS.entrySet()) if(!existing.contains(item.getKey())) { Asset asset=new Asset(); asset.setAssetSetId(setId); asset.setAssetType(item.getKey()); asset.setAssetName(item.getValue()); asset.setAssetStatus("NORMAL"); try { assetMapper.insert(asset); } catch(DuplicateKeyException ex) { if(assetMapper.selectCount(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,setId).eq(Asset::getAssetType,item.getKey()))==0) throw ex; } } }
    private void ensureCodeUnique(Long campusId,String code,Long excludedId) { if(buildingMapper.selectCount(Wrappers.<Building>lambdaQuery().eq(Building::getCampusId,campusId).eq(Building::getBuildingCode,code).ne(excludedId!=null,Building::getId,excludedId))>0) throw new BusinessException("同一校区内楼栋编码已存在"); }
    private void ensureNameUnique(Long campusId,String name,Long excludedId) { if(buildingMapper.selectCount(Wrappers.<Building>lambdaQuery().eq(Building::getCampusId,campusId).eq(Building::getBuildingName,name).ne(excludedId!=null,Building::getId,excludedId))>0) throw new BusinessException("同一校区内楼栋名称已存在"); }
    private void ensureRoomNoUnique(Long buildingId,String roomNo,Long excludedRoomId) { if(roomMapper.selectCount(Wrappers.<DormRoom>lambdaQuery().eq(DormRoom::getBuildingId,buildingId).eq(DormRoom::getRoomNo,roomNo).ne(excludedRoomId!=null,DormRoom::getId,excludedRoomId))>0) throw new BusinessException(409,"同一楼栋内寝室号已存在"); }
    private Campus requireEnabledCampus(Long id) { Campus item=campusMapper.selectById(id); if(item==null) throw new BusinessException(404,"校区不存在"); if(!Integer.valueOf(1).equals(item.getStatus())) throw new BusinessException("校区已停用"); return item; }
    private Building requireBuilding(Long id) { Building item=buildingMapper.selectById(id); if(item==null) throw new BusinessException(404,"楼栋不存在"); return item; }
    private Building requireDormBuilding(Long id) { Building item=requireBuilding(id); if(!DORM_BUILDING_TYPE.equals(item.getBuildingType())) throw new BusinessException("该楼栋不是宿舍楼，不能进入宿舍资源管理"); return item; }
    private Building requireEnabledDormBuilding(Long id) { Building item=requireDormBuilding(id); requireEnabledCampus(item.getCampusId()); if(!Integer.valueOf(1).equals(item.getStatus())) throw new BusinessException("楼栋已停用，不能新增宿舍资源"); return item; }
    private DormRoom requireRoom(Long id) { DormRoom item=roomMapper.selectById(id); if(item==null) throw new BusinessException(404,"寝室不存在"); return item; }
    private DormBed requireBed(Long id) { DormBed item=bedMapper.selectById(id); if(item==null) throw new BusinessException(404,"床位不存在"); return item; }
    private AssetSet requireAssetSet(Long id) { AssetSet item=assetSetMapper.selectById(id); if(item==null) throw new BusinessException(404,"资产套装不存在"); return item; }
    private Long admin() { Long id=AdminContext.getAdminId(); if(id==null) throw new BusinessException(401,"管理员登录已过期"); return id; }
    private String requiredText(String value,String message) { String text=trim(value); if(text==null) throw new BusinessException(message); return text; }
    private String trim(String value) { return value==null||value.trim().isEmpty()?null:value.trim(); }
    private String normalizeCode(String value) { String code=requiredText(value,"楼栋编码不能为空").toUpperCase(Locale.ROOT); if(!code.matches("[A-Z0-9_-]+")) throw new BusinessException("楼栋编码只能包含大写字母、数字、下划线或连字符"); return code; }
    private byte[] qr(String value) { try { BitMatrix matrix=new QRCodeWriter().encode(value,BarcodeFormat.QR_CODE,300,300); ByteArrayOutputStream stream=new ByteArrayOutputStream(); MatrixToImageWriter.writeToStream(matrix,"PNG",stream); return stream.toByteArray(); } catch(WriterException|IOException ex) { throw new BusinessException(500,"二维码生成失败"); } }
    private String nextToken() { for(int i=0;i<10;i++){ byte[] bytes=new byte[32]; RANDOM.nextBytes(bytes); StringBuilder token=new StringBuilder(64); for(byte b:bytes) token.append(String.format("%02x",b&0xff)); String value=token.toString(); if(assetSetMapper.selectCount(Wrappers.<AssetSet>lambdaQuery().eq(AssetSet::getQrToken,value))==0) return value; } throw new BusinessException(500,"二维码令牌生成失败"); }
    private static LinkedHashMap<String,String> assetItems(){ LinkedHashMap<String,String> items=new LinkedHashMap<String,String>(); items.put("BED","床"); items.put("BED_BOARD","床板"); items.put("DESK","书桌"); items.put("WARDROBE","衣柜"); items.put("STOOL","凳子"); return items; }
    private long number(Long value){return value==null?0:value.longValue();}
    private static final class BuildingStats { private final long roomCount; private final long bedCount; private final long assetSetCount; private final long checkinHistoryCount; private final long currentCheckinCount; private final boolean hasDormResources; private BuildingStats(long rooms,long beds,long sets,long history,long active){roomCount=rooms;bedCount=beds;assetSetCount=sets;checkinHistoryCount=history;currentCheckinCount=active;hasDormResources=rooms>0||beds>0||sets>0||history>0;} }
    private static final class RoomStats { private final long bedCount; private final long assetSetCount; private final long currentCheckinCount; private RoomStats(long beds,long sets,long active){bedCount=beds;assetSetCount=sets;currentCheckinCount=active;} }
}
