package com.qinghe.life.service.impl;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.qinghe.life.dto.DormQrRequest;
import com.qinghe.life.dto.StudentProfileSaveRequest;
import com.qinghe.life.entity.*;
import com.qinghe.life.exception.BusinessException;
import com.qinghe.life.mapper.*;
import com.qinghe.life.service.StudentDormService;
import com.qinghe.life.service.DormAssetHealth;
import com.qinghe.life.utils.UserContext;
import com.qinghe.life.vo.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class StudentDormServiceImpl implements StudentDormService {
    private static final Pattern QR = Pattern.compile("^QH-DORM-V1:([0-9a-fA-F]{64})$");
    private static final Set<String> ALLOWED = Collections.singleton("ENROLLED");
    private final StudentProfileMapper profileMapper; private final DormCheckinMapper checkinMapper; private final AssetSetMapper assetSetMapper; private final AssetMapper assetMapper; private final DormBedMapper bedMapper; private final DormRoomMapper roomMapper; private final BuildingMapper buildingMapper; private final CampusMapper campusMapper;
    public StudentDormServiceImpl(StudentProfileMapper profileMapper,DormCheckinMapper checkinMapper,AssetSetMapper assetSetMapper,AssetMapper assetMapper,DormBedMapper bedMapper,DormRoomMapper roomMapper,BuildingMapper buildingMapper,CampusMapper campusMapper){this.profileMapper=profileMapper;this.checkinMapper=checkinMapper;this.assetSetMapper=assetSetMapper;this.assetMapper=assetMapper;this.bedMapper=bedMapper;this.roomMapper=roomMapper;this.buildingMapper=buildingMapper;this.campusMapper=campusMapper;}
    @Override public StudentProfileVO getProfile(){return profileView(currentProfile());}
    @Override @Transactional(rollbackFor=Exception.class) public StudentProfileVO saveProfile(StudentProfileSaveRequest r){ Long userId=requireUser(); StudentProfile p=currentProfile(); if(p!=null){p.setContactPhone(r.getContactPhone().trim());profileMapper.updateById(p);return profileView(p);} Campus campus=enabledCampus(r.getCampusId());p=new StudentProfile();p.setUserId(userId);p.setRealName(required(r.getRealName(),"真实姓名"));p.setStudentNo(required(r.getStudentNo(),"学号"));p.setCampusId(campus.getId());p.setCollegeName(required(r.getCollegeName(),"学院"));p.setMajorName(required(r.getMajorName(),"专业"));p.setClassName(required(r.getClassName(),"班级"));p.setContactPhone(r.getContactPhone().trim());p.setStudentStatus("ENROLLED");p.setCurrentFlag(1);try{profileMapper.insert(p);}catch(DuplicateKeyException e){throw new BusinessException(409,"学号已被当前学生资料使用");}return StudentProfileVO.from(p,campus);}
    @Override public DormQrResolveVO resolveQr(DormQrRequest r){return qrView(context(r.getQrContent()));}
    @Override @Transactional(rollbackFor=Exception.class) public StudentDormVO checkIn(DormQrRequest r){ Long userId=requireUser(); StudentProfile p=currentProfile();if(p==null)throw new BusinessException("请先完成学生实名资料");if(!ALLOWED.contains(p.getStudentStatus()))throw new BusinessException("当前学籍状态不允许入住"); DormContext c=context(r.getQrContent());if(!p.getCampusId().equals(c.campus.getId()))throw new BusinessException("学生资料校区与二维码宿舍校区不一致"); if(hasActiveUser(userId))throw new BusinessException("您已有有效入住记录"); String unavailable=unavailableReason(c);if(unavailable!=null)throw new BusinessException(unavailable); DormCheckin in=new DormCheckin();in.setUserId(userId);in.setStudentProfileId(p.getId());in.setDormBedId(c.bed.getId());in.setAssetSetId(c.set.getId());in.setCheckinSource("STUDENT_QR");in.setCheckinStatus("ACTIVE");in.setActiveFlag(1);in.setStudentNoSnapshot(p.getStudentNo());in.setStudentStatusSnapshot(p.getStudentStatus());in.setCampusNameSnapshot(c.campus.getCampusName());in.setBuildingCodeSnapshot(c.building.getBuildingCode());in.setBuildingNameSnapshot(c.building.getBuildingName());in.setRoomNoSnapshot(c.room.getRoomNo());in.setBedNoSnapshot(c.bed.getBedNo());in.setAssetSetNoSnapshot(c.set.getAssetSetNo());try{checkinMapper.insert(in);}catch(DuplicateKeyException e){throw new BusinessException(409,"该床位或您的账户已有有效入住记录");} c.set.setStatus("OCCUPIED");assetSetMapper.updateById(c.set);return dormView(p,in,c.assets);}
    @Override public StudentDormVO myDorm(){StudentProfile p=currentProfile();if(p==null)return null;DormCheckin in=checkinMapper.selectOne(Wrappers.<DormCheckin>lambdaQuery().eq(DormCheckin::getUserId,requireUser()).eq(DormCheckin::getActiveFlag,1));if(in==null)return null;return dormView(p,in,names(in.getAssetSetId()));}
    private StudentProfile currentProfile(){Long id=requireUser();return profileMapper.selectOne(Wrappers.<StudentProfile>lambdaQuery().eq(StudentProfile::getUserId,id).eq(StudentProfile::getCurrentFlag,1));}
    private DormContext context(String qr){Matcher m=QR.matcher(qr==null?"":qr.trim());if(!m.matches())throw new BusinessException("二维码格式不正确");AssetSet set=assetSetMapper.selectOne(Wrappers.<AssetSet>lambdaQuery().eq(AssetSet::getQrToken,m.group(1).toLowerCase(Locale.ROOT)));if(set==null)throw new BusinessException(404,"二维码不存在或已失效");DormBed bed=bedMapper.selectById(set.getDormBedId());if(bed==null||!Integer.valueOf(1).equals(bed.getStatus()))throw new BusinessException("床位已停用");DormRoom room=roomMapper.selectById(bed.getDormRoomId());if(room==null||!Integer.valueOf(1).equals(room.getStatus()))throw new BusinessException("寝室已停用");Building building=buildingMapper.selectById(room.getBuildingId());Campus campus=campusMapper.selectById(room.getCampusId());if(building==null||campus==null||!Integer.valueOf(1).equals(building.getStatus())||!Integer.valueOf(1).equals(campus.getStatus())||!room.getCampusId().equals(building.getCampusId()))throw new BusinessException("宿舍目录不可用");if(!Integer.valueOf(1).equals(set.getQrStatus()))throw new BusinessException("二维码已停用");if(!Arrays.asList("AVAILABLE","OCCUPIED","MAINTENANCE","RETIRED").contains(set.getStatus()))throw new BusinessException("资产套装状态异常");return new DormContext(set,bed,room,building,campus,names(set.getId()));}
    private DormQrResolveVO qrView(DormContext c){DormQrResolveVO v=new DormQrResolveVO();String reason=unavailableReason(c);DormAssetHealth.Result health=DormAssetHealth.inspect(assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,c.set.getId())));v.setCampusName(c.campus.getCampusName());v.setBuildingName(c.building.getBuildingName());v.setRoomNo(c.room.getRoomNo());v.setBedNo(c.bed.getBedNo());v.setAssetSetCode(c.set.getAssetSetNo());v.setAssetSetStatus(c.set.getStatus());v.setAssetHealthStatus(health.getStatus());v.setAssetNames(c.assets);v.setAvailable(reason==null);v.setUnavailableReason(reason);return v;}
    private String unavailableReason(DormContext c){if(!"AVAILABLE".equals(c.set.getStatus())){if("OCCUPIED".equals(c.set.getStatus()))return "该床位当前已入住，暂不可入住";if("MAINTENANCE".equals(c.set.getStatus()))return "资产套装维护中，暂不可入住";return "资产套装已停用，暂不可入住";}DormAssetHealth.Result health=DormAssetHealth.inspect(assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,c.set.getId())));if(health.getUnavailableReason()!=null)return health.getUnavailableReason();if(hasActiveBed(c.bed.getId()))return "该床位当前已有有效入住记录，暂不可入住";return null;}
    private boolean hasActiveUser(Long userId){return checkinMapper.selectCount(Wrappers.<DormCheckin>lambdaQuery().eq(DormCheckin::getUserId,userId).eq(DormCheckin::getActiveFlag,1))>0;}
    private boolean hasActiveBed(Long bedId){return checkinMapper.selectCount(Wrappers.<DormCheckin>lambdaQuery().eq(DormCheckin::getDormBedId,bedId).eq(DormCheckin::getActiveFlag,1))>0;}
    private Campus enabledCampus(Long campusId){if(campusId==null)throw new BusinessException("请选择所属校区");Campus campus=campusMapper.selectById(campusId);if(campus==null||!Integer.valueOf(1).equals(campus.getStatus()))throw new BusinessException("请选择启用校区");return campus;}
    private StudentProfileVO profileView(StudentProfile profile){return profile==null?null:StudentProfileVO.from(profile,campusMapper.selectById(profile.getCampusId()));}
    private List<String> names(Long setId){List<Asset> assets=assetMapper.selectList(Wrappers.<Asset>lambdaQuery().eq(Asset::getAssetSetId,setId).orderByAsc(Asset::getId));List<String> names=new ArrayList<String>();for(Asset a:assets)names.add(a.getAssetName());return names;}
    private StudentDormVO dormView(StudentProfile p,DormCheckin in,List<String> assets){StudentDormVO v=new StudentDormVO();v.setRealName(p.getRealName());v.setMaskedStudentNo(mask(p.getStudentNo()));v.setCollegeName(p.getCollegeName());v.setMajorName(p.getMajorName());v.setClassName(p.getClassName());v.setStudentStatus(p.getStudentStatus());v.setMaskedContactPhone(maskPhone(p.getContactPhone()));v.setCampusName(in.getCampusNameSnapshot());v.setBuildingName(in.getBuildingNameSnapshot());v.setRoomNo(in.getRoomNoSnapshot());v.setBedNo(in.getBedNoSnapshot());v.setAssetSetCode(in.getAssetSetNoSnapshot());v.setAssetNames(assets);v.setCheckInTime(in.getCheckinTime());v.setCheckInStatus(in.getCheckinStatus());return v;}
    private Long requireUser(){Long id=UserContext.getUserId();if(id==null)throw new BusinessException(401,"未登录或登录已过期");return id;} private String required(String value,String label){if(value==null||value.trim().isEmpty())throw new BusinessException(label+"不能为空");return value.trim();} private String mask(String s){if(s==null||s.length()<5)return "***";return s.substring(0,2)+"***"+s.substring(s.length()-2);} private String maskPhone(String s){return s==null?null:s.replaceAll("^(\\d{3})\\d+(\\d{4})$","$1****$2");}
    private static final class DormContext { private final AssetSet set;private final DormBed bed;private final DormRoom room;private final Building building;private final Campus campus;private final List<String> assets;private DormContext(AssetSet set,DormBed bed,DormRoom room,Building building,Campus campus,List<String> assets){this.set=set;this.bed=bed;this.room=room;this.building=building;this.campus=campus;this.assets=assets;} }
}
