<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getBusinessOverview, getBusinessTrend, getShopSalesRanking } from '../api/admin-report'
import { getAdminOrders } from '../api/admin-order'
const router = useRouter(); const loading = ref(false); const overview = ref({ salesAmount: 0, orderCount: 0, paidPendingOrderCount: 0, deliveringOrderCount: 0, newUserCount: 0, activeShopCount: 0 }); const trend = ref([]); const ranks = ref([]); const orders = ref([])
const maxSales = computed(() => Math.max(1, ...trend.value.map(item => Number(item.salesAmount || 0))))
function money(value) { return '¥' + Number(value || 0).toFixed(2) }
function status(value) { return ({ PENDING_PAY: '待支付', PAID: '待接单', ACCEPTED: '待配送', DELIVERING: '配送中', COMPLETED: '已完成', CANCELLED: '已取消' })[value] || value || '-' }
async function load() { loading.value = true; try { const [a,b,c,d] = await Promise.all([getBusinessOverview(), getBusinessTrend({}), getShopSalesRanking({ top: 6 }), getAdminOrders({ page: 1, size: 8 })]); overview.value = { ...overview.value, ...(a || {}) }; trend.value = b || []; ranks.value = c || []; orders.value = d?.records || [] } finally { loading.value = false } }
onMounted(load)
</script>
<template><section class="dashboard" v-loading="loading"><div class="heading"><div><p>OPERATIONS OVERVIEW</p><h1>管理首页</h1><span>实时复用营业报表与订单数据；无数据时以 0 和明确空状态呈现。</span></div><el-button @click="load">刷新数据</el-button></div><div class="metric-grid"><article><span>今日营业额</span><strong>{{money(overview.salesAmount)}}</strong></article><article><span>今日订单数</span><strong>{{overview.orderCount||0}}</strong></article><article><span>待接单</span><strong>{{overview.paidPendingOrderCount||0}}</strong></article><article><span>配送中</span><strong>{{overview.deliveringOrderCount||0}}</strong></article><article><span>今日新增用户</span><strong>{{overview.newUserCount||0}}</strong></article><article><span>营业店铺数量</span><strong>{{overview.activeShopCount||0}}</strong></article></div><div class="main-grid"><el-card shadow="never"><template #header>最近 7 天营业趋势</template><div v-if="trend.length" class="trend"><div v-for="item in trend" :key="item.reportDate" class="bar"><i :style="{height: Math.max(4, Number(item.salesAmount||0)/maxSales*150)+'px'}"></i><span>{{item.reportDate?.slice(5)}}</span><b>{{money(item.salesAmount)}}</b></div></div><el-empty v-else description="暂无营业趋势数据" :image-size="62"/></el-card><el-card shadow="never"><template #header>店铺排行</template><el-table :data="ranks" size="small" empty-text="暂无店铺排行数据"><el-table-column type="index" label="#" width="45"/><el-table-column prop="shopName" label="店铺"/><el-table-column label="营业额" align="right"><template #default="{row}">{{money(row.salesAmount)}}</template></el-table-column></el-table></el-card></div><div class="main-grid lower"><el-card shadow="never"><template #header>最近订单</template><el-table :data="orders" size="small" empty-text="暂无最近订单"><el-table-column prop="orderNo" label="订单号" min-width="150"/><el-table-column prop="shopName" label="店铺"/><el-table-column label="状态"><template #default="{row}"><el-tag size="small">{{status(row.status)}}</el-tag></template></el-table-column><el-table-column label="实付" align="right"><template #default="{row}">{{money(row.payAmount)}}</template></el-table-column></el-table></el-card><el-card shadow="never"><template #header>常用管理</template><div class="quick"><el-button @click="router.push('/admin/orders')">订单管理</el-button><el-button @click="router.push('/admin/shops')">店铺管理</el-button><el-button @click="router.push('/admin/explore')">探店审核</el-button><el-button @click="router.push('/admin/reports')">营业报表</el-button></div></el-card></div></section></template>
<style scoped>.dashboard{max-width:1440px;margin:0 auto}.heading{display:flex;justify-content:space-between;gap:16px;margin-bottom:22px}.heading p{margin:0 0 6px;color:#5d7eb6;font-size:12px;font-weight:700;letter-spacing:.12em}.heading h1{margin:0;color:#213758}.heading span{display:block;margin-top:8px;color:#7c8ca4}.metric-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.metric-grid article{padding:18px;border:1px solid #e4ebf4;border-radius:10px;background:#fff}.metric-grid span{display:block;color:#7789a2;font-size:13px}.metric-grid strong{display:block;margin-top:10px;color:#25466e;font-size:23px}.main-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:16px;margin-top:16px}.trend{display:flex;align-items:end;gap:12px;min-height:196px;padding:12px 4px}.bar{display:flex;flex:1;min-width:0;align-items:center;flex-direction:column;justify-content:end;gap:5px}.bar i{width:70%;border-radius:6px 6px 0 0;background:linear-gradient(180deg,#6ca0e8,#355f9f)}.bar span,.bar b{overflow:hidden;max-width:100%;color:#71839c;font-size:11px;text-overflow:ellipsis;white-space:nowrap}.bar b{color:#4a6485;font-weight:500}.lower{grid-template-columns:1.4fr .7fr}.quick{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.quick .el-button{margin:0}@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(3,1fr)}.main-grid,.lower{grid-template-columns:1fr}}@media(max-width:560px){.heading{flex-direction:column}.metric-grid{grid-template-columns:repeat(2,1fr)}.metric-grid article{padding:13px}.metric-grid strong{font-size:19px}}</style>
