<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { batchDisableQr, batchReleaseAssets, batchRotateQr, createDormBed, createDormBuilding, createDormRoom, deleteDormBed, deleteDormBuilding, deleteDormRoom, downloadQr, downloadQrZip, generateAssetSet, getAssetSet, listAvailableDormBuildings, listDormBeds, listDormBuildings, listDormCampuses, listDormRooms, previewAssetRelease, previewQrDisable, previewQrRotate, supplementFixedAssets, updateDormAsset, updateDormBed, updateDormBedStatus, updateDormBuilding, updateDormBuildingStatus, updateDormRoom, updateDormRoomStatus } from '../api/adminDorm'
import { dormTagType, dormText } from '../utils/dormStatus'

const campuses=ref([]); const buildings=ref([]); const availableBuildings=ref([]); const rooms=ref([]); const beds=ref([])
const buildingTotal=ref(0); const roomTotal=ref(0); const selectedBuilding=ref(null); const activeRoom=ref(null); const assetDetail=ref(null); const selectedSetIds=ref([]); const qrDialog=ref(false); const qrPreviewUrl=ref(''); const qrPreviewLoading=ref(false); const qrBed=ref(null)
const buildingQuery=reactive({campusId:null,status:null,keyword:'',page:1,size:20}); const roomQuery=reactive({buildingId:null,page:1,size:10})
const buildingDialog=ref(false); const buildingEditing=ref(null); const roomDialog=ref(false); const roomEditing=ref(null); const bedDialog=ref(false); const bedEditing=ref(null); const assetDialog=ref(false); const assetEditing=ref(null); const saving=ref(false)
const assetBatchOpen=ref(false); const assetBatchAction=ref(''); const assetBatchPreview=ref(null); const assetBatchReason=ref(''); const assetBatchBusy=ref(false)
const buildingForm=reactive({buildingCode:'',buildingName:'',area:'',remark:'',status:1}); const roomForm=reactive({roomNo:'',floor:'',capacity:4,status:1,remark:''}); const bedForm=reactive({bedNo:'',status:1,remark:''}); const assetForm=reactive({assetStatus:'NORMAL',remark:''})
const assetStatusOptions=['NORMAL','REPAIR','SCRAPPED']; const statusText=value=>dormText('enabled',value)

function resetRoom(){ Object.assign(roomForm,{roomNo:'',floor:'',capacity:4,status:1,remark:''}) }
function resetBed(){ Object.assign(bedForm,{bedNo:'',status:1,remark:''}) }
function resetBuilding(){ Object.assign(buildingForm,{buildingCode:'',buildingName:'',area:'',remark:'',status:1}) }
async function loadCampuses(){ campuses.value=await listDormCampuses(); if(!buildingQuery.campusId&&campuses.value.length) buildingQuery.campusId=campuses.value[0].id }
async function loadAvailableBuildings(){ availableBuildings.value=buildingQuery.campusId?await listAvailableDormBuildings(buildingQuery.campusId):[] }
async function loadBuildings(){ if(!buildingQuery.campusId){ buildings.value=[]; buildingTotal.value=0; availableBuildings.value=[]; return } const data=await listDormBuildings({ ...buildingQuery, campusId:buildingQuery.campusId, status:buildingQuery.status??undefined, keyword:buildingQuery.keyword||undefined }); buildings.value=data.records; buildingTotal.value=data.total; await loadAvailableBuildings() }
async function changeCampus(){ selectedBuilding.value=null; activeRoom.value=null; assetDetail.value=null; rooms.value=[]; beds.value=[]; roomQuery.buildingId=null; buildingQuery.page=1; await loadBuildings() }
async function selectBuilding(item){ if(!item) return; selectedBuilding.value=item; activeRoom.value=null; assetDetail.value=null; beds.value=[]; roomQuery.buildingId=item.id; roomQuery.page=1; await loadRooms() }
async function selectAvailableBuilding(id){ await selectBuilding(availableBuildings.value.find(item=>item.id===id)) }
function openCreateBuilding(){ if(!buildingQuery.campusId) return ElMessage.warning('请先选择校区'); buildingEditing.value=null; resetBuilding(); buildingDialog.value=true }
function openEditBuilding(row){ buildingEditing.value=row; Object.assign(buildingForm,{buildingCode:row.buildingCode||'',buildingName:row.buildingName||'',area:row.area||'',remark:row.remark||'',status:row.status}); buildingDialog.value=true }
async function saveBuilding(){ if(!buildingQuery.campusId) return ElMessage.warning('请先选择校区'); saving.value=true; try { let saved; if(buildingEditing.value) { saved=await updateDormBuilding(buildingEditing.value.id,{...buildingForm,status:Number(buildingForm.status)}) } else { saved=await createDormBuilding({campusId:buildingQuery.campusId,...buildingForm,status:Number(buildingForm.status)}) } buildingDialog.value=false; await loadBuildings(); const refreshed=buildings.value.find(item=>item.id===saved.id)||saved; await selectBuilding(refreshed); ElMessage.success(buildingEditing.value?'宿舍楼已保存':'宿舍楼已新增') } finally { saving.value=false } }
async function toggleBuilding(row){ const next=row.status===1?0:1; const action=next===0?'停用':'启用'; await ElMessageBox.confirm(`确认${action}宿舍楼“${row.buildingName}”？${next===0?'当前仍有入住时系统会拒绝，请先办理退宿或换寝。':'重新启用后可恢复用于新增寝室。'}`,`${action}宿舍楼`,{type:'warning'}); await updateDormBuildingStatus(row.id,next); ElMessage.success(`宿舍楼已${action}`); await loadBuildings(); if(selectedBuilding.value?.id===row.id) selectedBuilding.value=buildings.value.find(item=>item.id===row.id)||null }
async function removeBuilding(row){ await ElMessageBox.confirm(`确认条件删除宿舍楼“${row.buildingName}”？只在没有寝室、床位、资产套装和入住历史时允许删除；有关联数据请改为停用。`,'删除宿舍楼',{type:'warning',confirmButtonText:'确认删除'}); await deleteDormBuilding(row.id); ElMessage.success('宿舍楼已删除'); if(selectedBuilding.value?.id===row.id){ selectedBuilding.value=null; activeRoom.value=null; assetDetail.value=null; rooms.value=[]; beds.value=[]; roomQuery.buildingId=null } await loadBuildings() }
async function loadRooms(){ if(!roomQuery.buildingId){ rooms.value=[]; roomTotal.value=0; return } const data=await listDormRooms(roomQuery); rooms.value=data.records; roomTotal.value=data.total }
async function showBeds(room){ activeRoom.value=room; assetDetail.value=null; beds.value=await listDormBeds(room.id) }
function openCreateRoom(){ if(!selectedBuilding.value) return ElMessage.warning('请先选择启用宿舍楼'); roomEditing.value=null; resetRoom(); roomDialog.value=true }
function openEditRoom(row){ roomEditing.value=row; Object.assign(roomForm,{roomNo:row.roomNo,floor:row.floor||'',capacity:row.capacity,status:row.status,remark:row.remark||''}); roomDialog.value=true }
async function saveRoom(){ if(!selectedBuilding.value) return; saving.value=true; try { if(roomEditing.value) { await updateDormRoom(roomEditing.value.id,{...roomForm,capacity:Number(roomForm.capacity),status:Number(roomForm.status)}); ElMessage.success('寝室已保存') } else { await createDormRoom({buildingId:selectedBuilding.value.id,...roomForm,capacity:Number(roomForm.capacity),status:Number(roomForm.status)}); ElMessage.success('寝室已新增') } roomDialog.value=false; await loadRooms(); await loadBuildings() } finally { saving.value=false } }
async function toggleRoom(row){ const next=row.status===1?0:1; const action=next===0?'停用':'启用'; await ElMessageBox.confirm(`确认${action}寝室“${row.roomNo}”？当前入住时系统会拒绝本操作。`,`${action}寝室`,{type:'warning'}); await updateDormRoomStatus(row.id,next); ElMessage.success(`寝室已${action}`); await loadRooms(); await loadBuildings() }
async function removeRoom(row){ await ElMessageBox.confirm(`确认安全删除寝室“${row.roomNo}”？已有床位、资产套装或入住历史时系统将拒绝删除并提示改为停用。`,'删除寝室',{type:'warning',confirmButtonText:'确认删除'}); await deleteDormRoom(row.id); ElMessage.success('寝室已删除'); if(activeRoom.value?.id===row.id){ activeRoom.value=null; beds.value=[]; assetDetail.value=null } await loadRooms(); await loadBuildings() }
function openCreateBed(){ if(!activeRoom.value) return; bedEditing.value=null; resetBed(); bedDialog.value=true }
function openEditBed(row){ bedEditing.value=row; Object.assign(bedForm,{bedNo:row.bedNo,status:row.status,remark:row.remark||''}); bedDialog.value=true }
async function saveBed(){ if(!activeRoom.value) return; saving.value=true; try { if(bedEditing.value){ await updateDormBed(bedEditing.value.id,{...bedForm,status:Number(bedForm.status)}); ElMessage.success('床位已保存') } else { await createDormBed(activeRoom.value.id,{bedNo:bedForm.bedNo,remark:bedForm.remark}); ElMessage.success('床位已新增') } bedDialog.value=false; await showBeds(activeRoom.value); await loadRooms() } finally { saving.value=false } }
async function toggleBed(row){ const next=row.status===1?0:1; const action=next===0?'停用':'启用'; await ElMessageBox.confirm(`确认${action}床位“${row.bedNo}”？当前入住时系统会拒绝本操作。`,`${action}床位`,{type:'warning'}); await updateDormBedStatus(row.id,next); ElMessage.success(`床位已${action}`); await showBeds(activeRoom.value) }
async function removeBed(row){ await ElMessageBox.confirm(`确认安全删除床位“${row.bedNo}”？已有资产套装或入住历史时系统将拒绝删除并提示改为停用。`,'删除床位',{type:'warning',confirmButtonText:'确认删除'}); await deleteDormBed(row.id); ElMessage.success('床位已删除'); await showBeds(activeRoom.value); await loadRooms() }
async function initializeSet(row){ await ElMessageBox.confirm(`为床位“${row.bedNo}”初始化固定五件资产（床、床板、书桌、衣柜、凳子）？重复操作不会重复创建。`,'初始化资产套装',{type:'warning'}); assetDetail.value=await generateAssetSet(row.id); rememberSet(); ElMessage.success('资产套装已就绪') }
async function showSet(row){ assetDetail.value=await getAssetSet(row.id); rememberSet() }
function rememberSet(){ if(assetDetail.value&&!selectedSetIds.value.includes(assetDetail.value.id)) selectedSetIds.value.push(assetDetail.value.id) }
function openEditAsset(asset){ assetEditing.value=asset; Object.assign(assetForm,{assetStatus:asset.assetStatus,remark:asset.remark||''}); assetDialog.value=true }
async function saveAsset(){ saving.value=true; try { await updateDormAsset(assetEditing.value.id,{...assetForm}); assetDialog.value=false; assetDetail.value=await getAssetSet(assetDetail.value.dormBedId); await showBeds(activeRoom.value); ElMessage.success('资产已保存') } finally { saving.value=false } }
async function supplementAssets(row){ assetDetail.value=await supplementFixedAssets(row.id); rememberSet(); await showBeds(activeRoom.value); ElMessage.success('已补齐缺失的固定资产') }
function saveBlob(blob,name){ const url=URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download=name; link.click(); setTimeout(()=>URL.revokeObjectURL(url),0) }
function revokeQrPreview(){ if(qrPreviewUrl.value){ URL.revokeObjectURL(qrPreviewUrl.value); qrPreviewUrl.value='' } }
async function showQr(row){ await showSet(row); qrBed.value=row; revokeQrPreview(); qrDialog.value=true; qrPreviewLoading.value=true; try { qrPreviewUrl.value=URL.createObjectURL(await downloadQr(assetDetail.value.id)) } catch(error) { qrDialog.value=false; ElMessage.error(error?.message||'二维码图片加载失败') } finally { qrPreviewLoading.value=false } }
function closeQrDialog(){ qrDialog.value=false; qrBed.value=null; revokeQrPreview() }
async function oneQr(){ if(assetDetail.value) saveBlob(await downloadQr(assetDetail.value.id),`${assetDetail.value.assetSetNo}.png`) }
async function manyQr(){ if(!selectedSetIds.value.length) return ElMessage.warning('请先查看资产套装'); saveBlob(await downloadQrZip(selectedSetIds.value),'dorm-asset-qrcodes.zip') }
async function beginAssetBatch(action){ if(!selectedSetIds.value.length) return ElMessage.warning('请先查看并选择要批量处理的资产套装'); const previewers={release:previewAssetRelease,disable:previewQrDisable,rotate:previewQrRotate}; assetBatchAction.value=action; assetBatchPreview.value=await previewers[action](selectedSetIds.value); assetBatchReason.value=''; assetBatchOpen.value=true }
async function submitAssetBatch(){ if(!assetBatchReason.value.trim()) return ElMessage.warning('请填写办理原因'); const preview=assetBatchPreview.value; if(preview.ineligibleCount) return ElMessage.warning('预览中存在不符合条件的套装，请调整已查看套装后重新预览'); const labels={release:'批量释放资产',disable:'批量停用二维码',rotate:'批量轮换二维码'}; await ElMessageBox.confirm(`确认${labels[assetBatchAction.value]} ${preview.eligibleCount} 个套装吗？任一失败将整批回滚。`,'最终确认',{type:'warning'}); const handlers={release:batchReleaseAssets,disable:batchDisableQr,rotate:batchRotateQr}; assetBatchBusy.value=true; try{ await handlers[assetBatchAction.value]({ids:selectedSetIds.value,reason:assetBatchReason.value.trim(),previewToken:preview.previewToken}); ElMessage.success('批量操作成功'); assetBatchOpen.value=false; selectedSetIds.value=[]; if(activeRoom.value) await showBeds(activeRoom.value); if(assetDetail.value) assetDetail.value=await getAssetSet(assetDetail.value.dormBedId) }finally{assetBatchBusy.value=false} }
onMounted(async()=>{ await loadCampuses(); await loadBuildings() })
onBeforeUnmount(revokeQrPreview)
</script>

<template>
  <section class="page">
    <el-card>
      <template #header>宿舍楼</template>
      <el-form inline>
        <el-form-item label="校区"><el-select v-model="buildingQuery.campusId" @change="changeCampus"><el-option v-for="item in campuses" :key="item.id" :label="item.campusName" :value="item.id"/></el-select></el-form-item>
        <el-form-item label="状态"><el-select v-model="buildingQuery.status" clearable @change="buildingQuery.page=1;loadBuildings()"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select></el-form-item>
        <el-form-item label="关键字"><el-input v-model="buildingQuery.keyword" clearable placeholder="编码或名称" @keyup.enter="buildingQuery.page=1;loadBuildings()"/></el-form-item>
        <el-button :disabled="!buildingQuery.campusId" @click="buildingQuery.page=1;loadBuildings()">查询</el-button>
        <el-button type="primary" :disabled="!buildingQuery.campusId" @click="openCreateBuilding">新增宿舍楼</el-button>
      </el-form>
      <p v-if="!buildingQuery.campusId" class="tip">请先选择校区。</p><p v-else class="tip">此处只显示真实类型为“宿舍楼”的目录；教学楼、图书馆等仍由通用楼栋目录维护。</p>
      <el-table :data="buildings" row-key="id" @row-click="selectBuilding"><el-table-column prop="buildingCode" label="编码"/><el-table-column prop="buildingName" label="宿舍楼"/><el-table-column prop="area" label="区域"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column prop="roomCount" label="寝室数"/><el-table-column prop="bedCount" label="床位数"/><el-table-column prop="currentCheckinCount" label="当前入住人数"/><el-table-column label="操作" width="340"><template #default="{row}"><el-button link type="primary" @click.stop="openEditBuilding(row)">编辑</el-button><el-button link :type="row.status===1?'warning':'success'" @click.stop="toggleBuilding(row)">{{row.status===1?'停用':'启用'}}</el-button><el-button link type="primary" @click.stop="selectBuilding(row)">查看寝室</el-button><el-button link type="danger" @click.stop="removeBuilding(row)">删除</el-button></template></el-table-column></el-table>
      <el-pagination v-model:current-page="buildingQuery.page" v-model:page-size="buildingQuery.size" :total="buildingTotal" layout="prev, pager, next" @current-change="loadBuildings"/>
    </el-card>

    <el-dialog v-model="buildingDialog" :title="buildingEditing?'编辑宿舍楼':'新增宿舍楼'" width="500px"><el-form label-width="100px"><el-form-item label="所属校区"><el-input :model-value="campuses.find(item=>item.id===buildingQuery.campusId)?.campusName||'请先选择校区'" disabled/></el-form-item><el-form-item label="楼栋类型"><el-input model-value="宿舍楼" disabled/></el-form-item><el-form-item label="楼栋编码" required><el-input v-model="buildingForm.buildingCode" :disabled="buildingEditing&&!buildingEditing.codeEditable" maxlength="32"/><div v-if="buildingEditing&&!buildingEditing.codeEditable" class="tip">已有寝室、床位、资产套装或入住历史，不能修改楼栋编码。</div></el-form-item><el-form-item label="楼栋名称" required><el-input v-model="buildingForm.buildingName" maxlength="100"/></el-form-item><el-form-item label="区域"><el-input v-model="buildingForm.area" maxlength="64"/></el-form-item><el-form-item label="备注"><el-input v-model="buildingForm.remark" type="textarea" maxlength="255" show-word-limit/></el-form-item><el-form-item label="状态"><el-select v-model="buildingForm.status"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select></el-form-item></el-form><template #footer><el-button @click="buildingDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveBuilding">保存</el-button></template></el-dialog>

    <el-card>
      <template #header>寝室</template>
      <el-form inline><el-form-item label="宿舍楼"><el-select v-model="roomQuery.buildingId" filterable :disabled="!buildingQuery.campusId" placeholder="选择启用宿舍楼" @change="selectAvailableBuilding"><el-option v-for="item in availableBuildings" :key="item.id" :label="`${item.buildingCode||'未编码'} · ${item.buildingName}`" :value="item.id"/></el-select></el-form-item><el-button :disabled="!buildingQuery.campusId" @click="loadRooms">查询</el-button><el-button type="primary" :disabled="!selectedBuilding" @click="openCreateRoom">新增寝室</el-button></el-form>
      <el-table :data="rooms"><el-table-column prop="roomNo" label="寝室号"/><el-table-column prop="floor" label="楼层"/><el-table-column prop="capacity" label="容量"/><el-table-column prop="bedCount" label="床位数"/><el-table-column prop="currentCheckinCount" label="当前入住"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="270"><template #default="{row}"><el-button link type="primary" @click="showBeds(row)">查看床位</el-button><el-button link type="primary" @click="openEditRoom(row)">编辑</el-button><el-button link :type="row.status===1?'warning':'success'" @click="toggleRoom(row)">{{row.status===1?'停用':'启用'}}</el-button><el-button link type="danger" @click="removeRoom(row)">删除</el-button></template></el-table-column></el-table>
      <el-pagination v-model:current-page="roomQuery.page" v-model:page-size="roomQuery.size" :total="roomTotal" layout="prev, pager, next" @current-change="loadRooms"/>
    </el-card>

    <el-card v-if="activeRoom">
      <template #header>床位与资产套装：{{activeRoom.roomNo}} 室</template>
      <el-button type="primary" :disabled="activeRoom.status!==1" @click="openCreateBed">新增床位</el-button>
      <el-table :data="beds"><el-table-column prop="bedNo" label="床位号"/><el-table-column label="目录状态"><template #default="{row}"><el-tag :type="dormTagType('enabled',row.status)">{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="当前入住"><template #default="{row}"><el-tag :type="row.currentCheckin?'warning':'success'">{{dormText('checkin',row.currentCheckin)}}</el-tag></template></el-table-column><el-table-column label="资产套装"><template #default="{row}"><span v-if="row.assetSetNo">{{row.assetSetNo}}</span><span v-else class="muted">未初始化</span></template></el-table-column><el-table-column label="套装占用"><template #default="{row}">{{row.assetSetNo?dormText('assetSet',row.assetSetStatus):'-'}}</template></el-table-column><el-table-column label="资产健康"><template #default="{row}"><el-tag v-if="row.assetSetNo" :type="dormTagType('health',row.assetHealthStatus)">{{dormText('health',row.assetHealthStatus)}}</el-tag><span v-else>-</span></template></el-table-column><el-table-column label="操作" width="400"><template #default="{row}"><el-button v-if="!row.assetSetNo" link type="primary" @click="initializeSet(row)">初始化资产套装</el-button><el-button v-else link type="primary" @click="showSet(row)">查看资产</el-button><el-button v-if="row.assetHealthStatus==='INCOMPLETE'" link type="warning" @click="supplementAssets(row)">补齐固定资产</el-button><el-button v-if="row.assetSetNo" link type="primary" @click="showQr(row)">查看二维码</el-button><el-button link type="primary" @click="openEditBed(row)">编辑</el-button><el-button link :type="row.status===1?'warning':'success'" @click="toggleBed(row)">{{row.status===1?'停用':'启用'}}</el-button><el-button link type="danger" @click="removeBed(row)">删除</el-button></template></el-table-column></el-table>
    </el-card>

    <el-card v-if="assetDetail"><template #header>资产套装：{{assetDetail.assetSetNo}}</template><el-descriptions :column="4" border><el-descriptions-item label="套装占用">{{dormText('assetSet',assetDetail.status)}}</el-descriptions-item><el-descriptions-item label="套装健康"><el-tag :type="dormTagType('health',assetDetail.healthStatus)">{{dormText('health',assetDetail.healthStatus)}}</el-tag></el-descriptions-item><el-descriptions-item label="二维码状态">{{dormText('qr',assetDetail.qrStatus)}}</el-descriptions-item><el-descriptions-item label="当前入住">{{dormText('checkin',assetDetail.currentCheckin)}}</el-descriptions-item></el-descriptions><p v-if="assetDetail.assetAbnormal" class="tip">资产异常：当前入住不会自动退宿或释放套装；新入住会被阻止。</p><el-table :data="assetDetail.assets"><el-table-column prop="assetName" label="资产名称"/><el-table-column label="资产类型"><template #default="{row}">{{dormText('assetType',row.assetType)}}</template></el-table-column><el-table-column label="单件状态"><template #default="{row}">{{dormText('assetStatus',row.assetStatus)}}</template></el-table-column><el-table-column prop="remark" label="备注"/><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="openEditAsset(row)">编辑</el-button></template></el-table-column></el-table><el-button type="primary" @click="oneQr">下载二维码 PNG</el-button><el-button @click="manyQr">下载已查看二维码</el-button><el-divider>批量安全操作（已查看 {{selectedSetIds.length}} 个套装）</el-divider><el-button type="warning" @click="beginAssetBatch('release')">批量释放资产</el-button><el-button type="danger" @click="beginAssetBatch('disable')">批量停用二维码</el-button><el-button type="primary" @click="beginAssetBatch('rotate')">批量轮换二维码</el-button></el-card>

    <el-dialog v-model="qrDialog" title="查看床位资产二维码" width="520px" @closed="closeQrDialog"><el-skeleton v-if="qrPreviewLoading" :rows="8" animated/><template v-else><div class="qr-preview"><img v-if="qrPreviewUrl" :src="qrPreviewUrl" alt="床位资产二维码"/><el-empty v-else description="二维码图片加载失败"/></div><el-descriptions :column="1" border><el-descriptions-item label="资产套装编号">{{assetDetail?.assetSetNo}}</el-descriptions-item><el-descriptions-item label="位置">{{selectedBuilding?.buildingName}} · {{activeRoom?.roomNo}} 室 · {{qrBed?.bedNo}} 床</el-descriptions-item><el-descriptions-item label="二维码状态">{{dormText('qr',assetDetail?.qrStatus)}}</el-descriptions-item></el-descriptions><p class="tip">安全提示：二维码令牌不会以文本形式显示；请仅向授权入住人员出示图片。</p></template><template #footer><el-button @click="closeQrDialog">关闭</el-button><el-button type="primary" :disabled="!assetDetail" @click="oneQr">下载二维码 PNG</el-button></template></el-dialog>

    <el-dialog v-model="roomDialog" :title="roomEditing?'编辑寝室':'新增寝室'" width="480px"><el-form label-width="90px"><el-form-item label="寝室号" required><el-input v-model="roomForm.roomNo" :disabled="roomEditing&&!roomEditing.roomNoEditable"/><div v-if="roomEditing&&!roomEditing.roomNoEditable" class="tip">已有资产套装，不能修改寝室号。</div></el-form-item><el-form-item label="楼层"><el-input v-model="roomForm.floor"/></el-form-item><el-form-item label="容量"><el-input-number v-model="roomForm.capacity" :min="1" :max="20"/></el-form-item><el-form-item label="状态"><el-select v-model="roomForm.status"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="roomForm.remark" type="textarea" maxlength="255"/></el-form-item></el-form><template #footer><el-button @click="roomDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRoom">保存</el-button></template></el-dialog>
    <el-dialog v-model="bedDialog" :title="bedEditing?'编辑床位':'新增床位'" width="420px"><el-form label-width="90px"><el-form-item label="床位号" required><el-input v-model="bedForm.bedNo" :disabled="bedEditing&&!bedEditing.bedNoEditable"/><div v-if="bedEditing&&!bedEditing.bedNoEditable" class="tip">已有资产套装，不能修改床位号。</div></el-form-item><el-form-item label="状态"><el-select v-model="bedForm.status"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="bedForm.remark" type="textarea" maxlength="255"/></el-form-item></el-form><template #footer><el-button @click="bedDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveBed">保存</el-button></template></el-dialog>
    <el-dialog v-model="assetDialog" title="编辑资产" width="420px"><el-form label-width="90px"><el-form-item label="资产状态"><el-select v-model="assetForm.assetStatus"><el-option v-for="item in assetStatusOptions" :key="item" :label="dormText('assetStatus',item)" :value="item"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="assetForm.remark" type="textarea" maxlength="255"/></el-form-item></el-form><template #footer><el-button @click="assetDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAsset">保存</el-button></template></el-dialog>
    <el-dialog v-model="assetBatchOpen" title="批量安全操作" width="540px"><el-alert v-if="assetBatchPreview" :title="`预览：符合条件 ${assetBatchPreview.eligibleCount} 个，当前入住 ${assetBatchPreview.currentCheckinCount} 个，不符合 ${assetBatchPreview.ineligibleCount} 个`" type="warning" :closable="false"/><p class="tip">仅在预览结果全部符合条件时才可提交；二维码轮换不会清空令牌，资产释放不会绕过当前入住。</p><el-form label-width="90px"><el-form-item label="办理原因" required><el-input v-model="assetBatchReason" type="textarea" maxlength="255" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="assetBatchOpen=false">取消</el-button><el-button type="primary" :loading="assetBatchBusy" @click="submitAssetBatch">确认提交</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.page{display:grid;gap:16px}.tip{margin:8px 0;color:var(--el-color-info);font-size:13px}.muted{color:var(--el-text-color-secondary)}
</style>
