<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { batchCheckout, batchGraduate, dropStudent, getAdminStudent, graduateStudent, listAdminStudents, previewBatchCheckout, previewGraduation, reinstateStudent, suspendStudent, transferStudentMajor } from '../api/adminDorm'

const query = reactive({ studentName:'', studentNo:'', collegeName:'', majorName:'', className:'', studentStatus:'', accommodationStatus:'', page:1, size:10 })
const rows = ref([]); const total = ref(0); const selected = ref([]); const detail = ref(null); const detailOpen = ref(false); const actionOpen = ref(false); const busy = ref(false); const action = ref(''); const current = ref(null)
const form = reactive({ collegeName:'', majorName:'', className:'', reason:'', checkoutDorm:false })
const title = { transfer:'转专业', suspend:'休学', drop:'退学', graduate:'毕业', reinstate:'复学' }
async function load(){ const data = await listAdminStudents({ ...query, ...Object.fromEntries(Object.entries(query).filter(([,v]) => v !== '')) }); rows.value=data.records; total.value=data.total }
function reset(){ Object.assign(form,{collegeName:'',majorName:'',className:'',reason:'',checkoutDorm:false}) }
async function show(row){ detail.value=await getAdminStudent(row.userId); detailOpen.value=true }
function begin(row, kind){ current.value=row; action.value=kind; reset(); if(kind==='transfer') Object.assign(form,{collegeName:row.collegeName,majorName:row.majorName,className:row.className}); actionOpen.value=true }
async function submit(){ if(!form.reason.trim()) return ElMessage.warning('请填写办理原因'); if(action.value==='transfer' && (!form.collegeName.trim()||!form.majorName.trim()||!form.className.trim())) return ElMessage.warning('请完整填写新学院、专业和班级'); const data={...form,reason:form.reason.trim()}; const handlers={transfer:transferStudentMajor,suspend:suspendStudent,drop:dropStudent,graduate:graduateStudent,reinstate:reinstateStudent}; await ElMessageBox.confirm(`确认${title[action.value]}该学生吗？此操作会保留历史资料。`,'二次确认',{type:'warning'}); busy.value=true; try{ await handlers[action.value](current.value.userId,data); ElMessage.success('办理成功'); actionOpen.value=false; await load(); if(detailOpen.value) detail.value=await getAdminStudent(current.value.userId) }finally{busy.value=false} }
function ids(){ return selected.value.map(v=>v.userId) }
async function batch(kind){ if(!ids().length) return ElMessage.warning('请先选择学生'); const preview=kind==='graduate'?await previewGraduation(ids()):await previewBatchCheckout(ids()); const asset=preview.assetSetCount||0; await ElMessageBox.confirm(`预览：符合条件 ${preview.eligibleCount} 人，当前入住 ${preview.currentCheckinCount} 人，将释放套装 ${asset} 个，不符合 ${preview.ineligibleCount} 人。确认后整批处理，任一失败将回滚。`,'批量预览确认',{type:'warning',confirmButtonText:'继续填写原因'}); const { value }=await ElMessageBox.prompt('请输入办理原因','二次确认',{inputPattern:/\S+/,inputErrorMessage:'办理原因不能为空'}); await ElMessageBox.confirm(`确认提交 ${preview.eligibleCount} 人的批量${kind==='graduate'?'毕业':'退宿'}吗？`,'最终确认',{type:'warning'}); busy.value=true; try{ const data={ids:ids(),reason:value.trim(),previewToken:preview.previewToken}; if(kind==='graduate') await batchGraduate(data); else await batchCheckout(data); ElMessage.success('批量办理成功'); selected.value=[]; await load() }finally{busy.value=false} }
onMounted(load)
</script>

<template>
  <section class="page">
    <el-card><template #header>学生学籍管理</template><el-form inline><el-form-item label="姓名"><el-input v-model="query.studentName" clearable/></el-form-item><el-form-item label="学号"><el-input v-model="query.studentNo" clearable/></el-form-item><el-form-item label="学院"><el-input v-model="query.collegeName" clearable/></el-form-item><el-form-item label="专业"><el-input v-model="query.majorName" clearable/></el-form-item><el-form-item label="班级"><el-input v-model="query.className" clearable/></el-form-item><el-form-item label="学籍"><el-select v-model="query.studentStatus" clearable><el-option label="在籍" value="ENROLLED"/><el-option label="休学" value="SUSPENDED"/><el-option label="退学" value="DROPPED"/><el-option label="毕业" value="GRADUATED"/></el-select></el-form-item><el-form-item label="住宿"><el-select v-model="query.accommodationStatus" clearable><el-option label="当前入住" value="IN_DORM"/><el-option label="未入住" value="NOT_IN_DORM"/></el-select></el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button></el-form></el-card>
    <el-card><template #header><div class="toolbar"><span>当前资料</span><el-space><el-button :disabled="busy" type="primary" @click="batch('graduate')">批量毕业</el-button><el-button :disabled="busy" type="warning" @click="batch('checkout')">批量退宿</el-button></el-space></div></template><el-table :data="rows" @selection-change="selected=$event"><el-table-column type="selection" width="48"/><el-table-column prop="realName" label="姓名"/><el-table-column prop="maskedStudentNo" label="学号"/><el-table-column prop="collegeName" label="学院"/><el-table-column prop="majorName" label="专业"/><el-table-column prop="className" label="班级"/><el-table-column prop="studentStatus" label="学籍"/><el-table-column prop="dormSummary" label="当前宿舍"/><el-table-column label="操作" width="310"><template #default="{row}"><el-button link @click="show(row)">详情</el-button><el-button v-if="row.studentStatus==='ENROLLED'" link type="primary" @click="begin(row,'transfer')">转专业</el-button><el-button v-if="row.studentStatus==='ENROLLED'" link type="warning" @click="begin(row,'suspend')">休学</el-button><el-button v-if="row.studentStatus==='ENROLLED'" link type="danger" @click="begin(row,'drop')">退学</el-button><el-button v-if="row.studentStatus==='ENROLLED'" link type="success" @click="begin(row,'graduate')">毕业</el-button><el-button v-if="row.studentStatus==='SUSPENDED'" link type="success" @click="begin(row,'reinstate')">复学</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
    <el-dialog v-model="detailOpen" title="学生资料与版本" width="720px"><el-descriptions v-if="detail" :column="2" border><el-descriptions-item label="姓名">{{detail.profile.realName}}</el-descriptions-item><el-descriptions-item label="学号">{{detail.profile.maskedStudentNo}}</el-descriptions-item><el-descriptions-item label="联系电话">{{detail.maskedContactPhone||'—'}}</el-descriptions-item><el-descriptions-item label="当前宿舍">{{detail.dormSummary}}</el-descriptions-item></el-descriptions><el-table v-if="detail" :data="detail.history" size="small" class="history"><el-table-column prop="collegeName" label="学院"/><el-table-column prop="majorName" label="专业"/><el-table-column prop="className" label="班级"/><el-table-column prop="studentStatus" label="状态"/><el-table-column prop="effectiveTime" label="生效"/><el-table-column prop="endTime" label="结束"/><el-table-column prop="changeReason" label="原因"/></el-table></el-dialog>
    <el-dialog v-model="actionOpen" :title="title[action]" width="520px"><el-form label-width="100px"><template v-if="action==='transfer'"><el-form-item label="新学院" required><el-input v-model="form.collegeName"/></el-form-item><el-form-item label="新专业" required><el-input v-model="form.majorName"/></el-form-item><el-form-item label="新班级" required><el-input v-model="form.className"/></el-form-item></template><el-form-item v-if="action==='suspend'" label="宿舍处理"><el-switch v-model="form.checkoutDorm" active-text="同时退宿" inactive-text="保留宿舍"/></el-form-item><el-form-item label="异动原因" required><el-input v-model="form.reason" type="textarea" maxlength="255" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="actionOpen=false">取消</el-button><el-button type="primary" :loading="busy" @click="submit">确认办理</el-button></template></el-dialog>
  </section>
</template>

<style scoped>.page{display:grid;gap:16px}.toolbar{display:flex;justify-content:space-between;align-items:center}.history{margin-top:16px}.el-pagination{justify-content:flex-end;margin-top:16px}</style>
