<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Edit, Plus, Refresh, Search, Upload } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getAdminShops } from '../api/admin-shop'
import { getCategories } from '../api/category'
import { createAdminGoods, getAdminGoods, getAdminGoodsCategories, getAdminGoodsDetail, updateAdminGoods, updateAdminGoodsStatus, updateAdminGoodsStock, uploadAdminGoodsImage } from '../api/admin-goods'
import goodsPlaceholder from '../assets/goods-placeholder.svg'

const loading = ref(false); const saving = ref(false); const imagePreparing = ref(false); const dialogVisible = ref(false)
const formRef = ref(); const imageFile = ref(null); const previewUrl = ref(''); const stores = ref([]); const shopCategories = ref([]); const goodsCategories = ref([]); const operating = reactive({})
const query = reactive({ page: 1, size: 10, keyword: '', shopId: null, shopCategoryId: null, goodsCategoryId: null, saleStatus: null })
const result = reactive({ records: [], total: 0 })
const form = reactive(defaultForm())
const rules = { shopId: [{ required: true, message: '请选择店铺', trigger: 'change' }], name: [{ required: true, message: '请填写商品名称', trigger: 'blur' }], price: [{ required: true, message: '请填写价格', trigger: 'change' }], stock: [{ required: true, message: '请填写库存', trigger: 'change' }] }
const imagePreview = computed(() => previewUrl.value || form.coverImage || goodsPlaceholder)
const formCategories = computed(() => goodsCategories.value.filter((item) => item.status === 1 || item.id === form.categoryId))
const queryCategories = computed(() => query.shopId ? goodsCategories.value.filter((item) => item.status === 1) : [])

function defaultForm() { return { id: null, shopId: null, categoryId: null, name: '', description: '', price: 0, stock: 0, saleStatus: 'ON_SALE', coverImage: '' } }
function resetImage() { imageFile.value = null; if (previewUrl.value) URL.revokeObjectURL(previewUrl.value); previewUrl.value = '' }
function resetForm() { Object.assign(form, defaultForm()); resetImage() }
async function loadLookups() { const [page, categories] = await Promise.all([getAdminShops({ page: 1, size: 100, status: 1 }), getCategories()]); stores.value = page.records || []; shopCategories.value = categories || [] }
async function loadGoodsCategories(shopId, includeDisabled = false) { goodsCategories.value = shopId ? await getAdminGoodsCategories({ shopId, ...(includeDisabled ? {} : { status: 1 }) }) : [] }
async function load() { loading.value = true; try { const page = await getAdminGoods({ ...query }); result.records = page.records || []; result.total = page.total || 0 } catch (error) { ElMessage.error(error.message || '商品列表加载失败') } finally { loading.value = false } }
function search() { query.page = 1; load() }
async function resetSearch() { Object.assign(query, { page: 1, size: 10, keyword: '', shopId: null, shopCategoryId: null, goodsCategoryId: null, saleStatus: null }); goodsCategories.value = []; await load() }
function changeSize(size) { query.size = size; query.page = 1; load() }
function openCreate() { resetForm(); dialogVisible.value = true }
async function openEdit(row) { try { Object.assign(form, await getAdminGoodsDetail(row.id)); resetImage(); await loadGoodsCategories(form.shopId, true); dialogVisible.value = true } catch (error) { ElMessage.error(error.message || '商品资料加载失败') } }
async function onImageChange(uploadFile) { const file = uploadFile.raw; if (!file) return; imagePreparing.value = true; try { const optimized = await containAndCompress(file); resetImage(); imageFile.value = optimized; previewUrl.value = URL.createObjectURL(optimized) } catch (error) { ElMessage.error(error.message || '图片处理失败') } finally { imagePreparing.value = false } }
async function containAndCompress(file) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) throw new Error('仅支持 jpg、jpeg、png 或 webp 图片'); if (file.size > 3 * 1024 * 1024) throw new Error('原图不能超过 3MB'); const url = URL.createObjectURL(file); try { const image = await new Promise((resolve, reject) => { const value = new Image(); value.onload = () => resolve(value); value.onerror = () => reject(new Error('图片内容无效')); value.src = url }); const scale = Math.min(800 / image.width, 800 / image.height, 1); const width = Math.max(1, Math.round(image.width * scale)); const height = Math.max(1, Math.round(image.height * scale)); const canvas = document.createElement('canvas'); canvas.width = 800; canvas.height = 800; const ctx = canvas.getContext('2d'); ctx.fillStyle = '#f6f8fb'; ctx.fillRect(0, 0, 800, 800); ctx.drawImage(image, (800 - width) / 2, (800 - height) / 2, width, height); let quality = 0.88; let blob = await toWebp(canvas, quality); while (blob.size > 300 * 1024 && quality > 0.5) { quality -= 0.08; blob = await toWebp(canvas, quality) } if (blob.size > 300 * 1024) throw new Error('图片压缩后仍超过 300KB，请选择更简单的图片'); return new File([blob], 'goods-image.webp', { type: 'image/webp' }) } finally { URL.revokeObjectURL(url) } }
function toWebp(canvas, quality) { return new Promise((resolve, reject) => canvas.toBlob((blob) => blob?.type === 'image/webp' ? resolve(blob) : reject(new Error('当前浏览器不支持 WebP 压缩')), 'image/webp', quality)) }
async function save() { if (!formRef.value || saving.value || imagePreparing.value) return; const valid = await formRef.value.validate().catch(() => false); if (!valid) return; saving.value = true; try { const payload = { shopId: form.shopId, categoryId: form.categoryId, name: form.name, description: form.description || null, price: form.price, stock: form.stock, saleStatus: form.saleStatus }; const saved = form.id ? await updateAdminGoods(form.id, payload) : await createAdminGoods(payload); Object.assign(form, saved); if (imageFile.value) Object.assign(form, await uploadAdminGoodsImage(saved.id, imageFile.value)); ElMessage.success('商品已保存'); dialogVisible.value = false; resetImage(); await load() } catch (error) { ElMessage.error(error.message || '商品保存失败') } finally { saving.value = false } }
async function switchStatus(row) { const next = row.saleStatus === 'ON_SALE' ? 'OFF_SALE' : 'ON_SALE'; try { await ElMessageBox.confirm(`确认${next === 'ON_SALE' ? '上架' : '下架'}“${row.name}”吗？`, '调整商品状态', { type: 'warning' }); operating[row.id] = true; await updateAdminGoodsStatus(row.id, { saleStatus: next }); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error.message || '状态调整失败') } finally { operating[row.id] = false } }
async function adjustStock(row) { try { const response = await ElMessageBox.prompt('请输入不小于 0 的库存数量', `调整“${row.name}”库存`, { inputValue: String(row.stock || 0), inputPattern: /^\d+$/, inputErrorMessage: '库存必须是整数' }); await updateAdminGoodsStock(row.id, { stock: Number(response.value) }); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error.message || '库存调整失败') } }
watch(() => query.shopId, async (shopId, previous) => { if (shopId !== previous) query.goodsCategoryId = null; await loadGoodsCategories(shopId) })
watch(() => form.shopId, async (shopId, previous) => { if (shopId !== previous) form.categoryId = null; await loadGoodsCategories(shopId, Boolean(form.id)) })
onMounted(async () => { try { await loadLookups() } catch (error) { ElMessage.error(error.message || '店铺数据加载失败') } await load() })
</script>

<template>
  <section class="admin-goods-page">
    <div class="page-heading"><div><p>GOODS ADMIN</p><h1>商品管理</h1><span>店铺类型、商品分类、店铺和销售状态分别筛选。</span></div><el-button type="primary" :icon="Plus" @click="openCreate">新增商品</el-button></div>
    <el-card class="filter-card" shadow="never"><el-form class="filter-form" @submit.prevent="search"><el-form-item label="商品名称"><el-input v-model="query.keyword" :prefix-icon="Search" clearable placeholder="商品名称" @keyup.enter="search" /></el-form-item><el-form-item label="店铺类型"><el-select v-model="query.shopCategoryId" clearable placeholder="全部店铺类型"><el-option v-for="item in shopCategories" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="店铺"><el-select v-model="query.shopId" clearable filterable placeholder="全部店铺"><el-option v-for="item in stores" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="商品分类"><el-select v-model="query.goodsCategoryId" clearable :disabled="!query.shopId" placeholder="先选择店铺"><el-option v-for="item in queryCategories" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="商品状态"><el-select v-model="query.saleStatus" clearable placeholder="全部状态"><el-option label="上架" value="ON_SALE" /><el-option label="下架" value="OFF_SALE" /></el-select></el-form-item><el-button type="primary" :icon="Search" :loading="loading" @click="search">查询</el-button><el-button @click="resetSearch">重置</el-button><el-button text :icon="Refresh" :loading="loading" @click="load">刷新</el-button></el-form></el-card>
    <el-card shadow="never"><el-table v-loading="loading" :data="result.records"><el-table-column label="主图" width="100"><template #default="{ row }"><el-image class="image-thumb" :src="row.coverImage || goodsPlaceholder" fit="contain" /></template></el-table-column><el-table-column prop="name" label="商品名称" min-width="140" /><el-table-column prop="shopName" label="店铺" min-width="130" /><el-table-column label="商品分类" min-width="110"><template #default="{ row }">{{ row.categoryName || '未分类' }}</template></el-table-column><el-table-column label="价格" width="100"><template #default="{ row }">￥{{ Number(row.price || 0).toFixed(2) }}</template></el-table-column><el-table-column prop="stock" label="库存" width="70" /><el-table-column label="状态" width="86"><template #default="{ row }"><el-tag :type="row.saleStatus === 'ON_SALE' ? 'success' : 'info'">{{ row.saleStatus === 'ON_SALE' ? '上架' : '下架' }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="230"><template #default="{ row }"><el-button text type="primary" :icon="Edit" @click="openEdit(row)">编辑</el-button><el-button text @click="adjustStock(row)">库存</el-button><el-button text :loading="operating[row.id]" @click="switchStatus(row)">{{ row.saleStatus === 'ON_SALE' ? '下架' : '上架' }}</el-button></template></el-table-column></el-table><el-pagination v-if="result.total" v-model:current-page="query.page" :page-size="query.size" :total="result.total" layout="total, prev, pager, next" @current-change="load" /></el-card>
    <el-dialog v-model="dialogVisible" :title="form.id ? '编辑商品' : '新增商品'" width="min(760px, calc(100vw - 28px))" @closed="resetImage"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="dialog-grid"><el-form-item label="所属店铺" prop="shopId"><el-select v-model="form.shopId" filterable placeholder="请选择店铺"><el-option v-for="item in stores" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="商品分类"><el-select v-model="form.categoryId" clearable :disabled="!form.shopId" placeholder="可暂不分类"><el-option v-for="item in formCategories" :key="item.id" :label="item.status === 1 ? item.name : `${item.name}（已停用，保留历史归属）`" :value="item.id" :disabled="item.status !== 1 && item.id !== form.categoryId" /></el-select><small v-if="form.categoryId && formCategories.find(item => item.id === form.categoryId)?.status === 0">该分类已停用；可保留当前归属，或改选启用分类。</small></el-form-item><el-form-item label="商品名称" prop="name"><el-input v-model="form.name" maxlength="100" /></el-form-item><el-form-item label="售价" prop="price"><el-input-number v-model="form.price" :min="0" :precision="2" /></el-form-item><el-form-item label="库存" prop="stock"><el-input-number v-model="form.stock" :min="0" /></el-form-item><el-form-item label="销售状态"><el-radio-group v-model="form.saleStatus"><el-radio label="ON_SALE">上架</el-radio><el-radio label="OFF_SALE">下架</el-radio></el-radio-group></el-form-item><el-form-item class="wide" label="商品简介"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="500" /></el-form-item></div><el-form-item label="商品主图"><div class="image-editor"><el-image class="image-preview" :src="imagePreview" fit="contain" /><div><el-upload accept=".jpg,.jpeg,.png,.webp" :auto-upload="false" :show-file-list="false" :disabled="imagePreparing || saving" :on-change="onImageChange"><el-button :icon="Upload" :loading="imagePreparing">选择图片</el-button></el-upload><el-button v-if="imageFile" text type="danger" @click="resetImage">移除本地图片</el-button><p>完整保留商品主体：等比缩放到 800×800 画布，浅色留白，优先 WebP 且不超过 300KB；仅保存时上传一次。</p></div></div></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" :disabled="imagePreparing" @click="save">保存</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.admin-goods-page{max-width:1440px;margin:0 auto}.page-heading{display:flex;justify-content:space-between;gap:16px;margin-bottom:20px}.page-heading p{margin:0;color:#5a7db7;font-size:12px;font-weight:700;letter-spacing:.12em}.page-heading h1{margin:4px 0;color:#213758}.page-heading span{color:#7e8ea5}.filter-card{margin-bottom:16px}.filter-form{display:flex;flex-wrap:wrap;align-items:flex-end;gap:0 12px}.filter-form .el-input,.filter-form .el-select{width:170px}.image-thumb{width:68px;height:68px;background:#f6f8fb;border-radius:8px}.dialog-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 18px}.wide{grid-column:1/-1}.image-editor{display:flex;gap:16px;align-items:center}.image-preview{width:168px;height:168px;background:#f6f8fb;border:1px solid #dce6f2;border-radius:10px}.image-editor p,small{display:block;max-width:360px;color:#7e8ea5;font-size:12px;line-height:1.6}@media(max-width:720px){.page-heading,.image-editor{flex-direction:column}.filter-form{display:grid;grid-template-columns:1fr}.filter-form .el-input,.filter-form .el-select{width:100%}.dialog-grid{grid-template-columns:1fr}.wide{grid-column:auto}.image-preview{width:100%;height:240px}}
</style>
