<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createAdminCoupon, getAdminCouponStats, getAdminCoupons, updateAdminCoupon, updateAdminCouponStatus } from '../api/admin-coupon'
import { getAdminShops } from '../api/admin-shop'
import PageHeader from '../components/PageHeader.vue'

const loading = ref(false); const dialogVisible = ref(false); const statsVisible = ref(false); const submitting = ref(false)
const result = reactive({ records: [], total: 0 }); const query = reactive({ page: 1, size: 10, status: '' }); const shops = ref([]); const stats = ref(null); const editingId = ref(null)
const blankForm = () => ({ name: '', couponType: 'CASH', discountAmount: null, discountRate: null, thresholdAmount: 0, totalStock: 1, receiveStartTime: '', receiveEndTime: '', useStartTime: '', useEndTime: '', shopId: null, perUserLimit: 1, status: 'DISABLED' })
const form = reactive(blankForm()); const money = (value) => Number(value || 0).toFixed(2)
async function load() { loading.value = true; try { const page = await getAdminCoupons({ ...query, status: query.status || undefined }); result.records = page.records || []; result.total = page.total || 0 } catch (error) { ElMessage.error(error.message || '优惠券列表加载失败') } finally { loading.value = false } }
async function loadShops() { try { shops.value = (await getAdminShops({ page: 1, size: 100, status: 1 })).records || [] } catch (error) { ElMessage.error(error.message || '店铺列表加载失败') } }
function openCreate() { editingId.value = null; Object.assign(form, blankForm()); dialogVisible.value = true }
function openEdit(row) { editingId.value = row.id; Object.assign(form, { ...blankForm(), ...row }); dialogVisible.value = true }
async function submit() { submitting.value = true; try { const body = { ...form, discountAmount: form.couponType === 'CASH' ? form.discountAmount : null, discountRate: form.couponType === 'DISCOUNT' ? form.discountRate : null }; if (editingId.value) await updateAdminCoupon(editingId.value, body); else await createAdminCoupon(body); ElMessage.success('保存成功'); dialogVisible.value = false; await load() } catch (error) { ElMessage.error(error.message || '保存失败') } finally { submitting.value = false } }
async function toggle(row) { const status = row.status === 'ENABLED' ? 'DISABLED' : 'ENABLED'; try { await ElMessageBox.confirm(`确认${status === 'ENABLED' ? '启用' : '停用'}“${row.name}”吗？`, '确认操作', { type: 'warning' }); await updateAdminCouponStatus(row.id, { status }); ElMessage.success('状态已更新'); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error.message || '状态更新失败') } }
async function openStats(row) { try { stats.value = await getAdminCouponStats(row.id); statsVisible.value = true } catch (error) { ElMessage.error(error.message || '统计加载失败') } }
onMounted(async () => { await Promise.all([load(), loadShops()]) })
</script>
<template>
  <section><PageHeader title="优惠管理" description="仅可编辑尚未开始领取的普通优惠券；已领取优惠券使用停用而不删除。" eyebrow="ADMIN COUPONS" />
    <el-card class="ui-card"><div class="toolbar"><el-radio-group v-model="query.status" @change="() => { query.page = 1; load() }"><el-radio-button label="">全部</el-radio-button><el-radio-button label="ENABLED">启用</el-radio-button><el-radio-button label="DISABLED">停用</el-radio-button></el-radio-group><el-button type="primary" @click="openCreate">新增优惠券</el-button></div><el-table v-loading="loading" :data="result.records"><el-table-column prop="name" label="名称" min-width="140" /><el-table-column label="优惠"><template #default="{ row }">{{ row.couponType === 'DISCOUNT' ? `${Number(row.discountRate || 0) * 10} 折` : `减 ¥${money(row.discountAmount)}` }}</template></el-table-column><el-table-column label="库存"><template #default="{ row }">{{ row.availableStock }}/{{ row.totalStock }}</template></el-table-column><el-table-column prop="receiveStartTime" label="领取开始" min-width="160" /><el-table-column prop="useEndTime" label="使用截止" min-width="160" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="230"><template #default="{ row }"><el-button text @click="openStats(row)">统计</el-button><el-button text :disabled="new Date(row.receiveStartTime) <= new Date()" @click="openEdit(row)">编辑</el-button><el-button text :type="row.status === 'ENABLED' ? 'danger' : 'primary'" @click="toggle(row)">{{ row.status === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table><el-pagination v-if="result.total" v-model:current-page="query.page" :page-size="query.size" :total="result.total" layout="total, prev, pager, next" @current-change="load" /></el-card>
    <el-dialog v-model="dialogVisible" :title="editingId ? '编辑优惠券' : '新增优惠券'" width="min(720px, calc(100vw - 28px))"><el-form label-width="108px"><el-form-item label="名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.couponType"><el-radio label="CASH">固定减免</el-radio><el-radio label="DISCOUNT">折扣</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.couponType === 'CASH'" label="优惠金额"><el-input-number v-model="form.discountAmount" :min="0.01" :precision="2" /></el-form-item><el-form-item v-else label="折扣率"><el-input-number v-model="form.discountRate" :min="0.0001" :max="0.9999" :step="0.01" :precision="4" /></el-form-item><el-form-item label="使用门槛"><el-input-number v-model="form.thresholdAmount" :min="0" :precision="2" /></el-form-item><el-form-item label="总库存"><el-input-number v-model="form.totalStock" :min="1" /></el-form-item><el-form-item label="适用店铺"><el-select v-model="form.shopId" filterable><el-option v-for="shop in shops" :key="shop.id" :label="shop.name" :value="shop.id" /></el-select></el-form-item><el-form-item label="领取时间"><el-date-picker v-model="form.receiveStartTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /> 至 <el-date-picker v-model="form.receiveEndTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item><el-form-item label="使用时间"><el-date-picker v-model="form.useStartTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /> 至 <el-date-picker v-model="form.useEndTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item><el-form-item label="初始状态"><el-radio-group v-model="form.status"><el-radio label="ENABLED">启用</el-radio><el-radio label="DISABLED">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">保存</el-button></template></el-dialog>
    <el-dialog v-model="statsVisible" title="领取与使用统计" width="420px"><el-descriptions v-if="stats" :column="1" border><el-descriptions-item label="领取总数">{{ stats.receivedCount }}</el-descriptions-item><el-descriptions-item label="已锁定">{{ stats.lockedCount }}</el-descriptions-item><el-descriptions-item label="已核销">{{ stats.usedCount }}</el-descriptions-item><el-descriptions-item label="已过期">{{ stats.expiredCount }}</el-descriptions-item></el-descriptions></el-dialog>
  </section>
</template>
<style scoped>.toolbar{display:flex;justify-content:space-between;gap:12px;margin-bottom:16px;align-items:center}.el-pagination{margin-top:16px;justify-content:flex-end}@media(max-width:680px){.toolbar{align-items:flex-start;flex-direction:column}}</style>
