<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ChatDotRound, Location, Plus, Star } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { getShops } from '../api/shop'
import { createExploreComment, createExplorePost, getExploreComments, getExplorePost, getExplorePosts, getFollowingFeed, getNearbyShops, likeExplorePost, unlikeExplorePost, uploadExploreImage } from '../api/explore'
import { followUser } from '../api/social'
import { useUserStore } from '../stores/user'

const router = useRouter()
const user = useUserStore()
const posts = ref([]); const postTotal = ref(0); const loading = ref(false); const sort = ref('latest'); const selected = ref(null); const detailVisible = ref(false); const comments = ref([]); const commentText = ref(''); const submitting = ref(false); const publishVisible = ref(false); const shops = ref([]); const nearby = ref([]); const nearbyLoading = ref(false); const imageFiles = ref([]); const previewUrl = ref(''); const previewVisible = ref(false)
const location = reactive({ longitude: '', latitude: '', radius: 3, categoryId: null, message: '尚未请求定位；不会保存您的实时位置。' })
const form = reactive({ shopId: null, title: '', content: '' })
const feedMode = ref('latest'); const feedCursor = reactive({ maxTime: null, offset: null, hasMore: false }); const feedLoading = ref(false); const following = reactive({}); const followSubmitting = reactive({}); const feedRequestVersion = ref(0)
const hasLocation = computed(() => location.longitude !== '' && location.latitude !== '')

const uploadingImages = computed(() => imageFiles.value.some(file => file.status === 'uploading' || file.status === 'ready'))
function images() { return imageFiles.value.filter(file => file.status === 'success' && file.url).map(file => file.url) }
function resetPublish() { Object.assign(form, { shopId: null, title: '', content: '' }); imageFiles.value = [] }
function beforeImageUpload(file) { const allowed = ['image/jpeg', 'image/png', 'image/webp'].includes(file.type); if (!allowed) { ElMessage.error('仅支持 jpg、jpeg、png 或 webp 图片'); return false } if (file.size > 5 * 1024 * 1024) { ElMessage.error('单张图片不能超过 5MB'); return false } return true }
async function uploadImage(request) { try { const url = await uploadExploreImage(request.file, event => { if (event.total) request.onProgress({ percent: Math.round(event.loaded * 100 / event.total) }) }); request.onSuccess({ url }) } catch (error) { request.onError(error) } }
function imageUploaded(response, uploadFile) { uploadFile.url = response.url }
function previewImage(uploadFile) { previewUrl.value = uploadFile.url; previewVisible.value = true }
function imageLimitExceeded() { ElMessage.warning('图片最多 9 张') }
function cancelPublish() { publishVisible.value = false; resetPublish() }
function formatTime(value) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '' }
function distance(value) { return Number(value || 0).toFixed(2) + ' km' }
function mergePosts(existing, incoming) { const seen = new Set(); return existing.concat(incoming || []).filter((post) => post?.id && !seen.has(post.id) && seen.add(post.id)) }
function resetFeedCursor() { feedCursor.maxTime = null; feedCursor.offset = null; feedCursor.hasMore = false }
function isFollowed(post) { return typeof following[post.userId] === 'boolean' ? following[post.userId] : Boolean(post.followedByMe) }
async function loadPosts() { const requestVersion = ++feedRequestVersion.value; loading.value = true; try { const data = await getExplorePosts({ page: 1, size: 20, sort: sort.value }); if (requestVersion !== feedRequestVersion.value || feedMode.value === 'following') return; posts.value = data.records || []; postTotal.value = data.total || 0 } catch (error) { if (requestVersion !== feedRequestVersion.value || feedMode.value === 'following') return; posts.value = []; postTotal.value = 0; ElMessage.error(error.message || '探店内容加载失败') } finally { if (requestVersion === feedRequestVersion.value) loading.value = false } }
async function loadFollowing(reset = true) { if (!user.isLoggedIn) return router.push({ name: 'login', query: { redirect: '/blogs' } }); if (!reset && !feedCursor.hasMore) return; const requestVersion = ++feedRequestVersion.value; if (reset) { posts.value = []; postTotal.value = 0; resetFeedCursor() } feedLoading.value = true; try { const data = await getFollowingFeed({ maxTime: reset ? undefined : feedCursor.maxTime, offset: reset ? undefined : feedCursor.offset, size: 10 }); if (requestVersion !== feedRequestVersion.value || feedMode.value !== 'following') return; posts.value = reset ? mergePosts([], data.records) : mergePosts(posts.value, data.records); feedCursor.maxTime = data.minTime; feedCursor.offset = data.offset; feedCursor.hasMore = Boolean(data.hasMore); postTotal.value = posts.value.length } catch (error) { if (requestVersion === feedRequestVersion.value && feedMode.value === 'following') ElMessage.error(error.message || '关注动态加载失败') } finally { if (requestVersion === feedRequestVersion.value) feedLoading.value = false } }
async function loadShops() { try { const data = await getShops({ page: 1, size: 50 }); shops.value = data.records || [] } catch { shops.value = [] } }
async function switchSort(value) { sort.value = value; await loadPosts() }
async function switchFeed(value) { feedRequestVersion.value++; feedMode.value = value; resetFeedCursor(); if (value === 'following') await loadFollowing(true); else await switchSort(value) }
function requestLocation() { if (!navigator.geolocation) { location.message = '当前浏览器不支持定位，请手动选择校区并填写经纬度。'; return } navigator.geolocation.getCurrentPosition(async (position) => { location.longitude = position.coords.longitude.toFixed(6); location.latitude = position.coords.latitude.toFixed(6); location.message = '已取得浏览器定位，仅用于本次附近店铺查询。'; await loadNearby() }, () => { location.message = '定位未授权或不可用。系统不会依据宿舍房间号推断位置；请手动选择校区并填写经纬度。' }, { enableHighAccuracy: false, timeout: 8000, maximumAge: 300000 }) }
async function loadNearby() { if (!hasLocation.value) { ElMessage.warning('请先授权定位，或手动填写校区中心经纬度'); return } nearbyLoading.value = true; try { const data = await getNearbyShops({ longitude: location.longitude, latitude: location.latitude, radius: location.radius, page: 1, size: 8, categoryId: location.categoryId || undefined }); nearby.value = data.records || [] } catch (error) { nearby.value = []; ElMessage.error(error.message || '附近店铺暂不可用') } finally { nearbyLoading.value = false } }
async function openDetail(post) { try { selected.value = await getExplorePost(post.id); const data = await getExploreComments(post.id, { page: 1, size: 50 }); comments.value = data.records || []; detailVisible.value = true } catch (error) { ElMessage.error(error.message || '内容详情加载失败') } }
async function toggleLike(post) { try { const result = post.liked ? await unlikeExplorePost(post.id) : await likeExplorePost(post.id); post.liked = result.liked; post.likeCount = result.likeCount; if (selected.value && selected.value.id === post.id) Object.assign(selected.value, result) } catch (error) { if (String(error.message || '').includes('登录')) router.push({ name: 'login', query: { redirect: '/blogs' } }); else ElMessage.error(error.message || '操作失败') } }
async function toggleFollow(post) { if (!user.isLoggedIn) return router.push({ name: 'login', query: { redirect: '/blogs' } }); if (post.userId === user.profile?.id || isFollowed(post) || followSubmitting[post.userId]) return; followSubmitting[post.userId] = true; try { const result = await followUser(post.userId); following[post.userId] = result.followedByMe; ElMessage.success(result.followedByMe ? '已关注' : '关注状态已更新') } catch (error) { ElMessage.error(error.message || '关注失败') } finally { followSubmitting[post.userId] = false } }
async function publish() { if (!form.shopId || !form.title.trim() || !form.content.trim()) { ElMessage.warning('请完整填写店铺、标题和内容'); return } if (uploadingImages.value) { ElMessage.warning('请等待全部图片上传完成'); return } if (imageFiles.value.some(file => file.status !== 'success')) { ElMessage.warning('请删除上传失败的图片后再发布'); return } submitting.value = true; try { await createExplorePost({ shopId: form.shopId, title: form.title.trim(), content: form.content.trim(), images: images() }); ElMessage.success('探店内容已发布'); publishVisible.value = false; resetPublish(); await loadPosts() } catch (error) { if (String(error.message || '').includes('登录')) router.push({ name: 'login', query: { redirect: '/blogs' } }); else ElMessage.error(error.message || '发布失败') } finally { submitting.value = false } }
async function submitComment() { if (!selected.value || !commentText.value.trim()) return; submitting.value = true; try { const item = await createExploreComment(selected.value.id, { content: commentText.value.trim() }); comments.value.push(item); selected.value.commentCount = Number(selected.value.commentCount || 0) + 1; const listed = posts.value.find(item => item.id === selected.value.id); if (listed) listed.commentCount = selected.value.commentCount; commentText.value = '' } catch (error) { ElMessage.error(error.message || '评论发布失败') } finally { submitting.value = false } }
onMounted(async () => { await Promise.all([loadPosts(), loadShops()]) })
onBeforeUnmount(() => { feedRequestVersion.value++ })
</script>

<template>
  <section class="explore-page">
    <div class="hero"><div><p>EXPLORE CAMPUS</p><h1>探店与附近</h1><span>记录校园好去处，发现此刻离你更近的店铺。</span></div><el-button type="primary" :icon="Plus" @click="publishVisible = true">发布探店</el-button></div>
    <el-card class="nearby-card" shadow="never"><div class="section-head"><div><h2><el-icon><Location /></el-icon> 附近店铺</h2><p>{{ location.message }}</p></div><el-space><el-button :icon="Location" @click="requestLocation">使用浏览器定位</el-button><el-button type="primary" :loading="nearbyLoading" @click="loadNearby">查询附近</el-button></el-space></div><div class="location-form"><el-input v-model="location.longitude" placeholder="经度" /><el-input v-model="location.latitude" placeholder="纬度" /><el-input-number v-model="location.radius" :min="0.1" :max="20" :precision="1" /><span>公里</span></div><el-skeleton :loading="nearbyLoading" animated><template #default><div v-if="nearby.length" class="nearby-grid"><article v-for="shop in nearby" :key="shop.id" class="nearby-shop" @click="router.push(`/shops/${shop.id}`)"><el-image :src="shop.coverImage" fit="cover"><template #error><div class="image-empty">店铺</div></template></el-image><div><strong>{{ shop.name }}</strong><p>{{ shop.address }}</p><span>{{ distance(shop.distance) }} · {{ Number(shop.score || 0).toFixed(1) }} 分</span></div></article></div><el-empty v-else description="完成定位或填写校区中心经纬度后，可查看附近营业店铺" :image-size="68" /></template></el-skeleton></el-card>
    <div class="feed-head"><div><h2>探店动态</h2><span>{{ feedMode === 'following' ? '关注用户的公开动态' : `共 ${postTotal} 条真实内容` }}</span></div><el-radio-group :model-value="feedMode" @change="switchFeed"><el-radio-button label="latest">推荐</el-radio-button><el-radio-button label="hot">热门</el-radio-button><el-radio-button label="following">关注</el-radio-button></el-radio-group></div>
    <el-skeleton :loading="loading || feedLoading" :rows="5" animated><template #default><div v-if="posts.length" class="post-list"><article v-for="post in posts" :key="post.id" class="post-card"><header><el-avatar :src="post.authorAvatar">{{ post.authorName?.slice(0, 1) }}</el-avatar><div><strong>{{ post.authorName }}</strong><p>{{ post.shopName }} · {{ formatTime(post.createdAt) }}</p></div><el-button v-if="post.userId !== user.profile?.id" text type="primary" :loading="followSubmitting[post.userId]" :disabled="isFollowed(post) || followSubmitting[post.userId]" @click="toggleFollow(post)">{{ isFollowed(post) ? '已关注' : '关注' }}</el-button></header><div class="post-body" @click="openDetail(post)"><h3>{{ post.title }}</h3><p>{{ post.content }}</p><div v-if="post.images?.length" class="image-grid"><el-image v-for="image in post.images" :key="image" :src="image" fit="cover" /></div></div><footer><el-button text :type="post.liked ? 'danger' : 'default'" :icon="Star" @click="toggleLike(post)">{{ post.likeCount || 0 }} 赞</el-button><span v-if="post.topLikers?.length" class="liker-list"><el-avatar v-for="liker in post.topLikers.slice(0, 5)" :key="liker.userId" :size="22" :src="liker.avatar" :title="liker.nickname">{{ liker.nickname?.slice(0, 1) }}</el-avatar></span><el-button text :icon="ChatDotRound" @click="openDetail(post)">{{ post.commentCount || 0 }} 评论</el-button></footer></article><el-button v-if="feedMode === 'following' && feedCursor.hasMore" :loading="feedLoading" @click="loadFollowing(false)">加载更多动态</el-button></div><el-empty v-else description="暂时没有可展示的探店内容，来发布第一条吧" /></template></el-skeleton>
    <el-dialog v-model="publishVisible" title="发布探店内容" width="min(680px, calc(100vw - 28px))" @closed="resetPublish"><el-form label-position="top"><el-form-item label="关联店铺"><el-select v-model="form.shopId" filterable placeholder="请选择营业店铺"><el-option v-for="shop in shops" :key="shop.id" :label="shop.name" :value="shop.id" /></el-select></el-form-item><el-form-item label="标题"><el-input v-model="form.title" maxlength="100" show-word-limit /></el-form-item><el-form-item label="体验内容"><el-input v-model="form.content" type="textarea" :rows="5" maxlength="2000" show-word-limit /></el-form-item><el-form-item label="探店图片"><el-upload v-model:file-list="imageFiles" action="#" drag list-type="picture-card" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" :auto-upload="true" :limit="9" :disabled="submitting" :http-request="uploadImage" :before-upload="beforeImageUpload" :on-exceed="imageLimitExceeded" :on-success="imageUploaded" :on-preview="previewImage"><el-icon><Plus /></el-icon><div class="el-upload__text">拖拽图片到这里，或点击选择</div><template #tip><div class="upload-tip">支持 jpg、jpeg、png、webp，单张不超过 5MB，最多 9 张。</div></template></el-upload></el-form-item></el-form><template #footer><el-button :disabled="submitting" @click="cancelPublish">取消</el-button><el-button type="primary" :loading="submitting" :disabled="uploadingImages" @click="publish">发布</el-button></template></el-dialog>
    <el-dialog v-model="previewVisible" title="图片预览" width="min(720px, calc(100vw - 28px))" append-to-body><img class="upload-preview" :src="previewUrl" alt="探店图片预览" /></el-dialog>
    <el-drawer v-model="detailVisible" :title="selected?.title || '探店详情'" size="min(680px, 100%)"><template v-if="selected"><p class="detail-meta">{{ selected.authorName }} · {{ selected.shopName }} · {{ formatTime(selected.createdAt) }}</p><p class="detail-content">{{ selected.content }}</p><div v-if="selected.images?.length" class="detail-images"><el-image v-for="image in selected.images" :key="image" :src="image" fit="cover" preview-teleported /></div><el-button :type="selected.liked ? 'danger' : 'primary'" :icon="Star" @click="toggleLike(selected)">{{ selected.likeCount || 0 }} 赞</el-button><el-divider>评论 {{ selected.commentCount || 0 }}</el-divider><div class="comment-box"><el-input v-model="commentText" type="textarea" maxlength="500" show-word-limit placeholder="写下你的看法" /><el-button type="primary" :loading="submitting" @click="submitComment">发表评论</el-button></div><el-empty v-if="!comments.length" description="暂无评论" :image-size="56" /><article v-for="comment in comments" :key="comment.id" class="comment"><el-avatar :src="comment.authorAvatar">{{ comment.authorName?.slice(0, 1) }}</el-avatar><div><strong>{{ comment.authorName }}</strong><p>{{ comment.content }}</p><span>{{ formatTime(comment.createdAt) }}</span></div></article></template></el-drawer>
  </section>
</template>

<style scoped>
.explore-page{max-width:1120px;margin:0 auto;padding-bottom:36px}.hero,.section-head,.feed-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.hero{margin:8px 0 24px}.hero p{margin:0 0 6px;color:#5d7eb6;font-size:12px;font-weight:700;letter-spacing:.14em}.hero h1{margin:0;color:#213758;font-size:30px}.hero span,.section-head p,.feed-head span{color:#7d8da5}.nearby-card{border-color:#e4ebf4}.section-head h2,.feed-head h2{margin:0;color:#294261;font-size:19px}.section-head p{margin:8px 0 0;font-size:13px}.location-form{display:flex;align-items:center;gap:10px;margin:16px 0}.location-form .el-input{width:160px}.nearby-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.nearby-shop{overflow:hidden;border:1px solid #e9eef5;border-radius:10px;cursor:pointer}.nearby-shop .el-image{width:100%;height:104px}.nearby-shop>div{padding:10px}.nearby-shop p{min-height:36px;margin:5px 0;color:#6f8098;font-size:12px}.nearby-shop span{color:#e2723b;font-size:12px}.image-empty{display:grid;height:100%;place-items:center;background:#edf3fb;color:#7d8da5}.feed-head{align-items:center;margin:28px 0 14px}.feed-head>div{display:flex;align-items:baseline;gap:10px}.post-list{display:grid;gap:14px}.post-card{padding:18px;border:1px solid #e5ebf4;border-radius:12px;background:#fff}.post-card header,.comment{display:flex;gap:10px}.post-card header p,.detail-meta,.comment p,.comment span{margin:4px 0 0;color:#8190a5;font-size:12px}.post-body{cursor:pointer}.post-body h3{margin:16px 0 8px;color:#273f5e}.post-body>p,.detail-content{margin:0;line-height:1.75;color:#43566e;white-space:pre-wrap}.image-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.image-grid .el-image{height:150px;border-radius:8px}.post-card footer{display:flex;gap:8px;margin-top:10px}.detail-images{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:16px 0}.detail-images .el-image{height:190px;border-radius:8px}.comment-box{display:flex;gap:10px;margin-bottom:18px}.comment-box .el-button{align-self:flex-end}.comment{padding:12px 0;border-bottom:1px solid #edf1f6}.comment p{color:#40536b;font-size:14px}.comment span{font-size:11px}.upload-tip{margin-top:8px;color:#7d8da5;font-size:12px}.upload-preview{display:block;max-width:100%;max-height:68vh;margin:auto;object-fit:contain}@media(max-width:760px){.hero,.section-head{flex-direction:column}.hero>.el-button,.section-head .el-space{width:100%}.location-form{flex-wrap:wrap}.location-form .el-input{width:calc(50% - 5px)}.nearby-grid{grid-template-columns:repeat(2,1fr)}.image-grid .el-image{height:110px}.comment-box{flex-direction:column}.comment-box .el-button{align-self:flex-end}}
</style>

<style scoped>
.post-card header{align-items:center}.post-card header>.el-button{margin-left:auto}.liker-list{display:inline-flex;align-items:center;gap:3px;margin-left:4px}.liker-list .el-avatar{border:1px solid #fff}
</style>
