<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ArrowLeft, Search, ShoppingCart } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { addCart, getCart } from '../api/cart'
import { getShop, getShopGoods, getShopGoodsCategories } from '../api/shop'
import { getToken } from '../utils/token'
import AsyncState from '../components/AsyncState.vue'
import GoodsCard from '../components/GoodsCard.vue'

const route = useRoute(); const router = useRouter(); const shop = ref(null); const goods = ref([]); const categories = ref([]); const loading = ref(true); const error = ref(''); const adding = reactive({}); const quantities = reactive({})
const filters = reactive({ keyword: '', categoryId: null }); const cart = ref({ totalCount: 0, totalAmount: 0 })
const canAdd = (item) => item.saleStatus === 'ON_SALE' && Number(item.stock) > 0
const maxQuantity = (item) => Math.max(1, Math.min(99, Number(item.stock || 0)))
const selectedCategoryLabel = computed(() => filters.categoryId ? (categories.value.find(item => item.id === filters.categoryId)?.name || '商品分类') : '全部商品')
async function loadCartEntry() { if (!getToken()) { cart.value = { totalCount: 0, totalAmount: 0 }; return } try { const data = await getCart(); const items = (data.shopGroups || []).flatMap(group => group.items || []); cart.value = { totalCount: items.reduce((sum, item) => sum + Number(item.quantity || 0), 0), totalAmount: items.reduce((sum, item) => sum + Number(item.subtotal || 0), 0) } } catch { cart.value = { totalCount: 0, totalAmount: 0 } } }
async function loadGoods() { const page = await getShopGoods(route.params.id, { page: 1, size: 100, keyword: filters.keyword || undefined, categoryId: filters.categoryId || undefined }); goods.value = page.records || []; goods.value.forEach(item => { if (!quantities[item.id]) quantities[item.id] = 1 }) }
async function load() { loading.value = true; error.value = ''; try { const [detail, categoryList] = await Promise.all([getShop(route.params.id), getShopGoodsCategories(route.params.id)]); shop.value = detail; categories.value = categoryList || []; await Promise.all([loadGoods(), loadCartEntry()]) } catch (exception) { error.value = exception.message || '店铺详情加载失败' } finally { loading.value = false } }
async function add(item) { if (!getToken()) { router.push({ name: 'login', query: { redirect: route.fullPath } }); return } adding[item.id] = true; try { await addCart({ goodsId: item.id, quantity: quantities[item.id] || 1 }); ElMessage.success('已加入购物车'); await loadCartEntry() } catch (exception) { ElMessage.error(exception.message || '加入购物车失败') } finally { adding[item.id] = false } }
function selectCategory(id) { filters.categoryId = id; loadGoods().catch(exception => ElMessage.error(exception.message || '商品加载失败')) }
function search() { loadGoods().catch(exception => ElMessage.error(exception.message || '商品加载失败')) }
watch(() => route.params.id, load)
onMounted(load)
</script>

<template>
  <section class="shop-page"><AsyncState :loading="loading" :error="error" :empty="!shop" empty-text="店铺不存在或暂不可用" :skeleton-rows="8" @retry="load"><header class="shop-hero"><el-image v-if="shop.coverImage" :src="shop.coverImage" fit="cover" class="shop-cover" /><div v-else class="shop-cover empty-cover">店铺封面</div><div class="shop-info"><div class="title-row"><div><p class="eyebrow">CAMPUS SHOP</p><h1>{{ shop.name }}</h1></div><el-tag type="success">营业中</el-tag></div><div class="rating">★ {{ Number(shop.score || 0).toFixed(1) }} <span>校内服务店铺</span></div><p class="intro">{{ shop.description || '为校园生活提供便捷的商品与服务。' }}</p><dl><div><dt>地址</dt><dd>{{ shop.address || '校内店铺' }}</dd></div><div><dt>电话</dt><dd>{{ shop.phone || '暂未提供' }}</dd></div></dl><el-button :icon="ArrowLeft" text @click="$router.back()">返回店铺列表</el-button></div></header><section class="goods-panel"><div class="goods-tools"><div><h2>{{ selectedCategoryLabel }}</h2><p>挑选喜欢的商品，售罄商品不可加入购物车。</p></div><el-input v-model="filters.keyword" clearable placeholder="搜索店内商品" :prefix-icon="Search" @keyup.enter="search"><template #append><el-button @click="search">搜索</el-button></template></el-input></div><nav class="category-nav"><el-button round :type="filters.categoryId === null ? 'primary' : 'default'" @click="selectCategory(null)">全部商品</el-button><el-button v-for="item in categories" :key="item.id" round :type="filters.categoryId === item.id ? 'primary' : 'default'" @click="selectCategory(item.id)">{{ item.name }}</el-button></nav><div v-if="goods.length" class="goods-grid"><GoodsCard v-for="item in goods" :key="item.id" :goods="item"><template #actions><el-button type="primary" size="small" :icon="ShoppingCart" :disabled="!canAdd(item)" :loading="adding[item.id]" @click="add(item)">{{ canAdd(item) ? '加购' : '售罄' }}</el-button></template></GoodsCard></div><el-empty v-else description="暂无匹配的在售商品" /></section><button class="cart-entry" type="button" @click="$router.push('/cart')"><el-icon><ShoppingCart /></el-icon><span><b>{{ cart.totalCount }}</b> 件已选商品</span><strong>￥{{ Number(cart.totalAmount || 0).toFixed(2) }}</strong><em>查看购物车</em></button></AsyncState>
  </section>
</template>

<style scoped>
.shop-page{max-width:1240px;margin:0 auto;padding-bottom:92px}.shop-hero{display:grid;grid-template-columns:minmax(280px,3fr) minmax(0,4fr);overflow:hidden;border:1px solid var(--qh-border);border-radius:16px;background:#fff;box-shadow:var(--qh-shadow-card)}.shop-cover{width:100%;aspect-ratio:3/2;background:#edf2f7}.empty-cover{display:grid;place-items:center;color:#94a3b8}.shop-info{padding:26px}.title-row,.goods-tools{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.eyebrow{margin:0;color:#5a7db7;font-size:12px;font-weight:700;letter-spacing:.12em}.shop-info h1{margin:6px 0;color:#203654;font-size:30px}.rating{color:#c07813;font-weight:700}.rating span{margin-left:8px;color:#718096;font-weight:400}.intro{margin:16px 0;color:#50627b;line-height:1.7}.shop-info dl{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:0 0 14px}.shop-info dl div{padding:10px 12px;border-radius:8px;background:#f7f9fc}.shop-info dt{color:#8492a6;font-size:12px}.shop-info dd{margin:4px 0 0;color:#334155}.goods-panel{margin-top:22px;padding:20px;border:1px solid var(--qh-border);border-radius:16px;background:#fff}.goods-tools h2{margin:0;color:#233a5e}.goods-tools p{margin:6px 0 0;color:#718096;font-size:13px}.goods-tools .el-input{max-width:340px}.category-nav{display:flex;gap:8px;margin:18px 0;overflow-x:auto;padding-bottom:4px;white-space:nowrap}.category-nav .el-button{margin:0}.goods-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.cart-entry{position:fixed;right:24px;bottom:22px;z-index:10;display:flex;align-items:center;gap:10px;padding:13px 16px;border:0;border-radius:12px;background:#203b68;color:#fff;box-shadow:0 12px 28px rgba(22,52,95,.28);cursor:pointer}.cart-entry b,.cart-entry strong{font-size:17px}.cart-entry em{font-style:normal;font-size:12px;opacity:.86}@media(max-width:980px){.goods-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.shop-page{padding-bottom:74px}.shop-hero{grid-template-columns:1fr}.shop-info{padding:20px}.goods-panel{padding:15px}.goods-tools{flex-direction:column}.goods-tools .el-input{max-width:none;width:100%}.goods-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cart-entry{right:0;bottom:0;left:0;justify-content:space-around;border-radius:0;padding:14px 10px}.cart-entry em{display:none}}@media(max-width:420px){.goods-grid{grid-template-columns:1fr}.shop-info dl{grid-template-columns:1fr}}
</style>
